#!/usr/bin/env python3
"""Validate and render accepted assignment design and its analysis."""
import argparse
from itertools import combinations
from phase3_audit import ROOT, read, table, number, build as time_audit
from phase5_report import decision
from design_data import assignments, assignment_schedule, when


def build():
    _,live=time_audit()
    p,policy,tasks=assignments(); d=read('decisions/topic_decisions.yaml')
    scheduled={r['id']:r for r in assignment_schedule()}
    policy=decision('assignment'); grading=decision('grading'); project=decision('project')
    project_analysis=read('analysis/phase5_plan.yaml')['project']
    topics={t['id']:t for t in read('analysis/normalized_topics.yaml')['topics']}
    groups={g['id']:g for g in d['scope_decisions']}; sessions={s['id']:s for s in d['lecture_plan']}
    outcomes={o['id'] for o in read('config/course.yaml')['learning_outcomes']}
    by_id={a['id']:a for a in tasks}; agg=policy['aggregation']
    assert len(tasks)==len(by_id)==agg['offered_count']
    assert 0<agg['counted_count']<=len(tasks) and policy['authorship']=='individual'
    for a in tasks:
        assert 'due_window' not in a, 'Accepted schedule duplicated in analysis'
        plan=scheduled[a['id']]
        a['release_after']=plan['last_session']
        a['earliest_due_week']=max(sessions[k]['week'] for k in a['prerequisites'])+policy['schedule_policy']['duration_days']/7
        a['due_window']=when(plan['start'])+' → '+when(plan['end'])
        a['release_stages']=['Full assignment released after all assessed prerequisites; 21 calendar days with original releases retained and one-week overlaps allowed.']
        assert set(a['group_ids'])<=groups.keys() and set(a['outcomes'])<=outcomes
        assert set(a['prerequisites'])<=sessions.keys() and a['release_after'] in sessions
        assert max(sessions[k]['week'] for k in a['prerequisites'])<=a['earliest_due_week']
        assert sessions[a['release_after']]['week']<=a['earliest_due_week']
        assert len(a['hours'])==2 and 0<a['hours'][0]<=a['hours'][1]
        for e in a['evidence_refs']:
            obs=topics[e['topic_id']]['sources'][e['source']]['evidence'][e['index']]
            assert obs['evidence_kind']=='assessment'
    covered=[]
    for row in p['alignment']:
        assert set(row['groups'])<=groups.keys() and set(row['assignments'])<=by_id.keys()
        covered+=row['groups']
    assert set(covered)=={g['id'] for g in groups.values() if g['role']=='core'}, 'Core alignment incomplete'
    assert len(covered)==len(set(covered)), 'Duplicate Core alignment'
    assert 'rubric_proposal' not in p, 'Rubrics deferred by instructor'
    for revision in p['curriculum_revision_proposals']:
        assert revision['state']=='accepted'
        assert set(revision['topic_ids'])<=topics.keys()
        assert revision['live_minutes_added']==0
    assert policy['llm_use']['report_state'].startswith('accepted')
    hours=[sum(a['hours'][i] for a in tasks) for i in (0,1)]
    subsets=list(combinations(tasks,agg['counted_count']))
    selected=[min(sum(a['hours'][0] for a in subset) for subset in subsets),max(sum(a['hours'][1] for a in subset) for subset in subsets)]
    active_project=[sum(m['student_hours'][i] for m in project_analysis['milestones']) for i in (0,1)]
    attendance=project['presentation_plan']['slot_minutes']/60
    video_effort=[sum(v['student_effort_minutes'][i] for v in read('analysis/phase3_proposal.yaml')['videos'])/60 for i in (0,1)]
    def session_label(sid):
        s=sessions[sid];return f'{s["week"]}.{s["slot"]}'
    def refs(a):
        result=[]
        for e in a['evidence_refs']:
            obs=topics[e['topic_id']]['sources'][e['source']]['evidence'][e['index']]
            link=obs.get('url') or '../'+obs['path']
            pages=obs.get('pdf_pages',[])
            if pages:link+='#page='+str(pages[0])
            result.append((f'- [{e["source"]}: {e["topic_id"]}]({link})'+(f', PDF pp. {pages[0]}–{pages[1]}' if pages else '')+'. '+obs['claim']+' '+obs.get('qualification','')).rstrip())
        return result
    intro=('Generated by `python3 scripts/assignment_report.py` from [assignment analysis](../analysis/assignment_proposal.yaml), '
           '[accepted policy](../decisions/assignment_decisions.md), frozen curriculum and normalized evidence. '
           '**Individual work and best-three-of-four grading are accepted. Three-week windows, original release points, PPO-use direction and LLM report are accepted; exact January dates remain provisional. Assignment scope and bounded Core implementation revisions are accepted. Workloads remain estimates; rubrics are deferred.**')
    out=['# Accepted assignment design','',intro,'',p['recommendation'],'',
         '**Accepted grading:** '+agg['formula']+'. '+agg['completion_rule']+' Each counted score can contribute '+f"{grading['categories_percent']['assignments']/agg['counted_count']:.2f}"+' course percentage points (exactly 20/3).','',
         table(['Assignment','Initial release after','Accepted timing window','Active student hours'],[[a['id']+' — '+a['title'],session_label(a['release_after']),a['due_window'],f'{a["hours"][0]}–{a["hours"][1]}'] for a in tasks]),'',
         f'Attempting all four: **{hours[0]}–{hours[1]} active hours**. Attempting exactly three: approximately {selected[0]}–{selected[1]}, depending on selection. '
         'Best-three grading can still lead students to attempt all four; do not budget every student as doing only three. '+p['workload_assumptions'],'']
    for a in tasks:
        out += ['## '+a['id']+' — '+a['title'],'',a['purpose'],'',
                '**Learning outcomes:** '+', '.join(a['outcomes'])+'. **Last prerequisite:** '+session_label(max(a['prerequisites'],key=lambda k:(sessions[k]['week'],sessions[k]['slot'])))+'.','',
                *[f'{i}. {t}' for i,t in enumerate(a['tasks'],1)],'',
                '**Decision boundary:** High-level scope accepted; concrete task construction and pilot remain future work.','',
                '**Grading design:** '+a.get('grading_design','Use automatic update checks; no separate hand-worked target submission.'),'',
                '**Starter code/support:** '+a['starter'],'',
                '**Staged release:** '+ ' '.join(a['release_stages']),'',
                '**Displacement and scope:** '+a['displacement'],'',
                '**Exam connection:** '+a['exam_bridge'],'',
                'Evidence below motivates bounded reuse; source-course workload and full algorithm requirements are not copied.','',*refs(a),'']
    out += ['## Submission, support and compute','',policy['accepted_design']['submission_proposal'],'',policy['accepted_design']['starter_strategy'],'',p['compute_targets'],'',policy['accepted_design']['delivery'],'',
            '## Rubric','',policy['refinements']['rubric'],'',
            '## LLM use: accepted report; final rubric deferred','',
            '**Accepted:** '+policy['llm_use']['disclosure']+' '+policy['llm_use']['no_credit_rule'],'',
            *('- '+x for x in policy['llm_use']['report_requirements']),'',
            p['llm_operational_proposal']['interpretation'],'',p['llm_operational_proposal']['grading_scope_pending'],'',
            p['llm_operational_proposal']['exam_checks'],'',
            '## Best-three fairness and evidence','',p['fairness_audit'],'',p['drop_policy_consequence'],'',
            '## Deferred work','',*('- '+x for x in policy['deferred_to_semester']),'',p['boundary'],'']
    out += ['## Accepted bounded curriculum revisions', '']
    for r in p['curriculum_revision_proposals']:
        out += ['### '+r['id'], '', '**Accepted:** '+r['change'], '',
                '**Why:** '+r['reason'], '', '**Displacement:** '+r['displacement'], '',
                '**Prerequisites:** '+r['prerequisites'], '', '**Live time:** '+r['live_reallocation'], '',
                '**Student effort:** '+r['student_time'], '', '**Delivery:** '+r['delivery'], '']
    out += ['## Selective primary-source checks', '', 'These verify algorithm structure for the recommendations; they are not assigned readings.', '']
    for e in p['primary_checks']:
        out += [f'- {e["claim"]} [{e["title"]}]({e["url"]}), {e["locator"]}; checked {e["retrieved"]}.']
    out += ['']
    staff=p['staffing_audit']
    staff_minutes=[sum(v[i] for v in staff['manual_minutes_per_submission'].values()) for i in (0,1)]
    audit=['# Assignment alignment and preliminary workload audit','',
           'Generated by `python3 scripts/assignment_report.py`. Accepted task scope and individual/best-three policy are distinguished from effort estimates. '
           'This is a Phase 5 planning audit, not final syllabus/design freeze.','',
           '## Result','',
           'The accepted design covers intended Core assessment paths with logged Double DQN and IQL implementation revisions and maximization bias clarified as Core. Weekly teaching topics and minutes are unchanged. '
           'The accepted 21-day rule retains original releases and allows one-week overlaps. Calendar mapping, January A4 compatibility and the deferred Week 13 conflict remain Phase 6 checks. The scaffold/runtime assumptions have not been piloted.','',
           '**Accepted best-three qualification:** '+p['drop_policy_consequence'],'',
           '## Core alignment','',
           table(['Frozen Core groups','Proposed assignment evidence','Other assessment path / scope limit'],[['; '.join(row['groups']),', '.join(row['assignments']) or 'No coding assignment required',row['other']] for row in p['alignment']]),'',
           'The implementation-bearing groups (planning, prediction, control, approximation, deep value and policy estimators) have direct opportunities in A1–A3. '
           'Dropping one of these tasks leaves its corresponding per-student implementation evidence incomplete. This is an acknowledged consequence of accepted aggregation, not a claim that exam answers prove coding mastery.','',
           '## Prerequisites and deadline pressure','',
           table(['Assignment','Release / final prerequisite','Scheduling consequence'],[[a['id'],session_label(a['release_after'])+' / '+session_label(max(a['prerequisites'],key=lambda k:(sessions[k]['week'],sessions[k]['slot']))),a['due_window']] for a in tasks]),'',
           '- Relative schedule (without breaks): A1 4.2–7.2; A2 6.2–9.2; A3 8.2–11.2; A4 12.2–15.2. A1/A2 overlap during 6.2–7.2; A2/A3 during 8.2–9.2.',
           '- A1 now shares Week 7 with project design; A3 is due in Week 11, after the Week 10 progress deadline. Midterm windows stay unchanged; later exam options may still coincide with deadlines. Exams cannot assume completed assignment work or feedback.',
           '- A4 relative 15.2 must be mapped to the official calendar to verify the earlier second-week-of-January target and separation from the project report. No exact date is invented.',
           '- The project presentation/midterm 3 clash remains intentionally deferred to the semester. See the Phase 6 workload audit for the updated combined schedule.', '',
           '## Partial out-of-class workload','',
           table(['Component','Estimated active hours / attendance','Qualification'],[
               ['All four assignments',f'{hours[0]}–{hours[1]}','Low confidence; includes writeup and disclosure'],
               ['Exactly three assignments',f'{selected[0]}–{selected[1]}','Depends on which task is omitted; not everyone will attempt only three'],
               ['Project active work',f'{active_project[0]}–{active_project[1]}','Includes staged work and final report; excludes session attendance'],
               ['Presentation attendance',number(attendance),'Own slot only, including own talk; do not add talk time again'],
               ['Two required videos, total student effort',f'{number(video_effort[0])}–{number(video_effort[1])}','Playback already included'],
               ['Student readings','0','Outside current planning'],
               ['Midterm preparation and attendance','Not estimated','Exam durations/calendar not finalized'],
               ['Routine review / unscheduled practice','Not estimated','Cannot claim this partial subtotal is total workload']]),'',
           f'If all four assignments are attempted, the specified project/assignment/video/presentation subtotal is approximately '
           f'**{number(hours[0]+active_project[0]+attendance+video_effort[0])}–{number(hours[1]+active_project[1]+attendance+video_effort[1])} hours**. '
           'This excludes exams, ordinary study, lecture attendance and unattended compute. Ranges are estimates, not measured performance or a feasibility guarantee.','',
           '## Fairness and staff workload','',p['fairness_audit'],'',
           table(['Assignment','Estimated routine manual minutes per submission'],[[k,f'{v[0]}–{v[1]}'] for k,v in staff['manual_minutes_per_submission'].items()]),'',
           f'All four submissions: {staff_minutes[0]}–{staff_minutes[1]} minutes per student, or N × {staff_minutes[0]}/60 to N × {staff_minutes[1]}/60 staff-hours for N students. At an illustrative 60 students, this is {staff_minutes[0]}–{staff_minutes[1]} hours across the four assignments. This is not an enrollment assumption. '+staff['confidence'],'',
           *('- '+x for x in staff['controls']),'',staff['risk'],'',
           '## Live-time result','',
           f'Frozen teaching remains {live[0]} minutes plus {live[1]} administration, leaving {number(live[2])} usable minutes. '
           'Assignment materials/support are proposed asynchronously. Exams and presentations remain outside lectures. Accepted bounded revisions substitute within existing 6.2 and 12.2 examples, adding zero live minutes; pilot support needs remain uncertain. No new prerequisite video or reading is assigned.','',
           '## Before acceptance and release','',
           '- Bounded Double DQN/IQL mastery revisions are accepted. Apply the latest three-week scheduling rule and check the earlier January target against official dates.',
           '- Finalize rubric and penalty scope with concrete assignments; accepted LLM-report requirements need no further approval. Prepare one example report at that stage.',
           '- Before release, recover/build and test starter code, dependencies, deterministic checks and laptop run budgets. Source PDFs and reference scaffolds are evidence, not a verified deliverable.',
           '- Keep assignment feedback and midterm questions aligned with content taught before each exam; A4 completion is not required for midterm 3.',
           '- Complete combined workload/calendar verification before final syllabus freeze. Phase 5 high-level design is complete by instructor acceptance; final syllabus/design freeze depends on Phase 6 checks.','']
    return {'output/assignments.md':'\n'.join(out),'output/audits/assignment_alignment.md':'\n'.join(audit)}


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for name,content in build().items():
        path=ROOT/name
        if args.check:assert path.exists() and path.read_text()==content,f'Stale generated file: {name}'
        else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
    print('Assignment design valid: prerequisite windows, four-task policy, Core alignment, accepted revision boundaries and evidence references checked; high-level scope accepted; concrete artifacts deferred.')


if __name__=='__main__':main()
