#!/usr/bin/env python3
"""Generate the shared per-session source index: output/lectures/session_sources.md.

    python3 scripts/build_session_sources.py [--check]

Shared by Claude and ChatGPT. A read-only compilation of existing records, so nothing is restated by hand:

  * decisions/topic_decisions.yaml   lecture plan (minutes, activity, pacing, segments) and topic-group
                                      scope, role, mastery and delivery
  * decisions/assignment_decisions.md assignments whose prerequisites include the session
  * decisions/video_decisions.md     prerequisite videos required before the session
  * analysis/normalized_topics.yaml  per-topic Sutton & Barto sections and source-course evidence

Old-deck and reference-course references are the PDF page numbers recorded in the evidence (used
consistently; they may differ from PPTX slide numbers where decks have hidden slides). The index adds no
decisions; edit the inputs and regenerate. --check exits non-zero if the file is stale.
"""
import argparse, re, sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'output/lectures/session_sources.md'
REL = '../../'                                     # from output/lectures/ to the repository root
SOURCE_NAMES = {'current_course': 'Current course (local)', 'silver_rl': 'Silver', 'berkeley_cs285': 'CS285',
                'stanford_cs234': 'CS234', 'stanford_cs224r': 'CS224R',
                'foundations-deep-rl-abbeel': 'Abbeel (Foundations of Deep RL)', 'sutton': 'Sutton slides'}


def yaml_block(path):
    return yaml.safe_load(re.findall(r'```yaml\n(.*?)```', (ROOT / path).read_text(encoding='utf-8'), re.S)[0])


def pages(p):
    if not p:
        return ''
    return f'p. {p[0]}' if len(p) == 1 or p[0] == p[-1] else f'pp. {p[0]}–{p[-1]}'


def link(ev):
    target, first = ev.get('url') or ev.get('path'), (ev.get('pdf_pages') or [None])[0]
    if not target:                                   # reading pointer / catalog entry: link its provenance
        prov = (ev.get('provenance') or [{}])[0]
        url = prov.get('source_url')
        label = f"{ev.get('evidence_kind', 'entry').replace('_', ' ')}: {prov.get('locator') or ev.get('locator', '')}"
        return f'[{label}]({url})' if url else label
    if ev.get('url'):
        href = target + (f'#page={first}' if first else '')
        label = target.rsplit('/', 1)[-1]
    else:
        href = REL + target.replace(' ', '%20') + (f'#page={first}' if first else '')
        label = Path(target).name
    return f'[{label}]({href})'


def anchor(topic_id):
    return 'topic-' + topic_id.replace('_', '-')


def build():
    td = yaml.safe_load((ROOT / 'decisions/topic_decisions.yaml').read_text(encoding='utf-8'))
    groups = {g['id']: g for g in td['scope_decisions']}
    assignments = yaml_block('decisions/assignment_decisions.md')['assignments']
    videos = yaml_block('decisions/video_decisions.md')['videos']
    nt = yaml.safe_load((ROOT / 'analysis/normalized_topics.yaml').read_text(encoding='utf-8'))
    topics = {t['id']: t for t in nt['topics']}
    titles = {s['id']: f"{s['week']}.{s['slot']}" for s in td['lecture_plan']}

    L = ['<!-- Generated by scripts/build_session_sources.py; do not edit. Shared by Claude and ChatGPT. -->', '',
         '# Session source index', '',
         'One place to look up everything recorded for each session. **Read-only compilation, not a new authority:** '
         'the accepted plan and scope come from `decisions/topic_decisions.yaml`, assignment and video dependencies '
         'from their decision files, book and source evidence from `analysis/normalized_topics.yaml`. Edit those and '
         'regenerate.', '',
         'Page numbers are the PDF pages recorded in the evidence. They are used consistently but can differ from PPTX '
         'slide numbers where a deck has hidden slides. Evidence shows where a source treats a topic; it is not a vote '
         'for inclusion, and a missing source is not evidence that the topic was not taught.', '']
    used_paths = {e.get('path') for t in topics.values() for s in t.get('sources', {}).values()
                  for e in s.get('evidence', []) if e.get('path')}
    unmapped = sorted(p.name for p in (ROOT / 'sources/current_course').glob('*.pptx')
                      if f'sources/current_course/{p.stem}.pdf' not in used_paths)
    if unmapped:
        L += ['Local decks with no page-level evidence (added or not exported when the evidence was collected); '
              'inspect them directly: ' + ', '.join(f'`{n}`' for n in unmapped) + '.', '']

    L += ['## Sessions', '']
    for s in td['lecture_plan']:
        sid = s['id']
        L += [f"### {s['week']}.{s['slot']} {s['title']} (`{sid}`)", '',
              f"- **Teaching:** {s['teaching_minutes']} min (range {s['teaching_range'][0]}–{s['teaching_range'][1]})"
              + (f"; plus {s['administration_minutes']} min administration" if s.get('administration_minutes') else '')
              + f"; confidence {s.get('confidence', 'n/a')}",
              f"- **Requires:** " + (', '.join(f"{titles.get(r, '?')} `{r}`" for r in s['requires'])
                                     if s.get('requires') else 'configured entry background'),
              f"- **Worked activity:** {s['worked_activity']}",
              f"- **Pacing note:** {s['feasibility_note']}"]
        if s.get('segments'):
            mins = lambda g: g['minutes'] if 'minutes' in g else td['constraints'][g['accepted_minutes_ref']]
            L.append('- **Segments:** ' + '; '.join(f"{g['label']} ({mins(g)} min)" for g in s['segments']))
        deps = [f"{a['id']} {a['title']} (release week {a['schedule']['release_week']})"
                for a in assignments if sid in a.get('prerequisites', [])]
        if deps:
            L.append('- **Prerequisite for:** ' + '; '.join(deps))
        vids = [v['id'] for v in videos if v.get('before') == sid]
        if vids:
            L.append('- **Students watch first:** ' + ', '.join(f'`{v}`' for v in vids)
                     + ' (see `decisions/video_decisions.md`)')
        L += ['', '| Topic group | Role · mastery · delivery | Accepted scope | Topics |', '| --- | --- | --- | --- |']
        for gid in s['group_ids']:
            g = groups[gid]
            tl = ', '.join(f'[{t}](#{anchor(t)})' if t in topics else f'`{t}`' for t in g.get('topic_ids', []))
            L.append(f"| {g.get('display_name', gid)} (`{gid}`) | {g['role']} · {', '.join(g['mastery'])} · "
                     f"{', '.join(g['delivery'])} | {g['scope']} | {tl} |")
        L.append('')

    L += ['## Topics', '', 'Topics referenced by the sessions above, with the sessions that use them.', '']
    by_topic = {}
    for s in td['lecture_plan']:
        for gid in s['group_ids']:
            for t in groups[gid].get('topic_ids', []):
                by_topic.setdefault(t, []).append(f"{s['week']}.{s['slot']}")
    for tid in sorted(by_topic, key=lambda t: (min(float(x) for x in by_topic[t]), t)):
        t = topics.get(tid)
        L += [f'<a id="{anchor(tid)}"></a>', f"### {t['name'] if t else tid} (`{tid}`)", '',
              f"Sessions: {', '.join(dict.fromkeys(by_topic[tid]))}.", '']
        if t is None:
            L += ['No normalized evidence record.', '']
            continue
        refs = t.get('book_mapping', {}).get('rl_book', {}).get('references', [])
        if refs:
            L.append('- **Sutton & Barto:** ' + '; '.join(
                f"§{r['section']} {r.get('section_title', '')} (printed {pages(r.get('printed_pages'))}, "
                f"[PDF {pages(r.get('pdf_pages'))}]({REL}sources/RLbook2020.pdf#page={r['pdf_pages'][0]}))"
                if r.get('pdf_pages') else f"§{r['section']} {r.get('section_title', '')}" for r in refs))
        for src in ['current_course'] + [k for k in SOURCE_NAMES if k != 'current_course']:
            info = t.get('sources', {}).get(src)
            if not info or not info.get('evidence'):
                continue
            items = []
            for ev in info['evidence']:
                item = f"{link(ev)} {pages(ev.get('pdf_pages'))}"
                if src == 'current_course' and ev.get('path', '').endswith('.pdf'):
                    pptx = (ROOT / ev['path']).with_suffix('.pptx')
                    if pptx.exists():
                        item += f" (deck: `{pptx.name}`)"
                items.append(item + (f" — {ev['claim']}" if ev.get('claim') else ''))
            L.append(f"- **{SOURCE_NAMES[src]}** ({info.get('coverage', 'unknown')}):")
            L += [f'  - {i}' for i in items]
        L.append('')
    return '\n'.join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--check', action='store_true', help='exit non-zero if the index is stale')
    a = ap.parse_args()
    text = build()
    if a.check:
        current = OUT.read_text(encoding='utf-8') if OUT.exists() else ''
        if current != text:
            sys.exit(f'{OUT.relative_to(ROOT)} is stale; run python3 scripts/build_session_sources.py')
        print('session source index current')
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)} ({text.count(chr(10)) + 1} lines)')


if __name__ == '__main__':
    main()
