#!/usr/bin/env python3
"""Write a read-only Markdown text view of a Claude-rendered deck, for review (docs/lecture_workflow.md step 6).

    python3 scripts/deck_text_view_claude.py <deck.pptx> <out.md>

Lists each slide's spec id (slide name), title, text, tables and speaker notes, plus the deck's SHA-256 so the
view can be matched to the saved deck it describes. Generated; never edit by hand.
"""
import hashlib, sys
from pathlib import Path
from pptx import Presentation


def main(deck, out):
    deck, out = Path(deck), Path(out)
    prs = Presentation(deck)
    lines = [f'<!-- Generated by scripts/deck_text_view_claude.py from {deck.name}; do not edit. -->', '',
             f'# Text view: {deck.name}', '', f'SHA-256 `{hashlib.sha256(deck.read_bytes()).hexdigest()}`', '']
    for n, s in enumerate(prs.slides, 1):
        title = s.shapes.title.text_frame.text if s.shapes.title is not None else ''
        lines += [f'## {n}. {s._element.cSld.get("name") or "(no id)"} — {title}', '']
        for sh in s.shapes:
            if s.shapes.title is not None and sh.shape_id == s.shapes.title.shape_id:
                continue
            if sh.has_table:
                rows = [[c.text.replace('\n', ' ') for c in r.cells] for r in sh.table.rows]
                lines += ['| ' + ' | '.join(rows[0]) + ' |', '|' + ' --- |' * len(rows[0])]
                lines += ['| ' + ' | '.join(r) + ' |' for r in rows[1:]] + ['']
            elif sh.shape_type == 6:
                texts = [t for t in sh._element.xpath('.//a:t/text()') if t.strip()]
                lines += [f'*Diagram `{sh.name}`:* ' + ' · '.join(texts), '']
            elif sh.shape_type == 13:
                lines += [f'*Image `{sh.name}`*', '']
            elif sh.has_text_frame and sh.text_frame.text.strip():           # includes drawn deco: labels (R14)
                for p in sh.text_frame.paragraphs:
                    if p.text.strip():
                        lines.append('  ' * p.level + '- ' + p.text.strip())
                lines.append('')
        if s.has_notes_slide and s.notes_slide.notes_text_frame.text.strip():
            lines += ['**Notes:**', '', *('> ' + l for l in s.notes_slide.notes_text_frame.text.strip().splitlines()), '']
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')


if __name__ == '__main__':
    main(*sys.argv[1:3])
