#!/usr/bin/env python3
"""Audit the internal design and frozen syllabus; render views without writing the DOCX/PDF."""
import argparse
from itertools import combinations
from phase3_audit import ROOT, read, table, number, build as time_audit
from phase4_audit import build as curriculum_audit
from phase5_report import decision
from design_data import assignments, assignment_schedule, milestone_when
from schedule_report import build as timeline
from syllabus_report import check_content, build as syllabus_markdown


def build():
    _, live = time_audit()
    curriculum_views = curriculum_audit()
    cfg = read('config/course.yaml')
    curriculum = read('decisions/topic_decisions.yaml')
    review = read('analysis/phase6_review.yaml')
    calendar = read('decisions/schedule_decisions.yaml')
    analysis, policy, tasks = assignments()
    grading, project, videos, readings = [decision(k) for k in ('grading','project','video','reading')]
    sessions = curriculum['lecture_plan']; by_id = {s['id']: s for s in sessions}
    schedule = assignment_schedule()
    keys = ('id','week','slot','title','teaching_minutes','administration_minutes')
    assert [{k:s[k] for k in keys} for s in sessions] == review['weekly_baseline']
    assert calendar['accepted_lecture_count'] == len(sessions)
    assert sum(grading['categories_percent'].values()) == 100
    assert sum(grading['midterm_weights_percent']) == grading['categories_percent']['midterms']
    assert sum(m['weight_percent'] for m in project['milestones']) == grading['categories_percent']['project']
    assert readings['required_readings'] == [] and not grading['final_exam_required']
    assert policy['schedule_policy']['duration_days'] == 21
    assert not review['calendar']['session_dates'], 'Dated mapping needs a dedicated post-Phase-7 audit; do not silently certify it.'
    label = lambda k: f'{by_id[k]["week"]}.{by_id[k]["slot"]}'
    intro = ('Generated by `python3 scripts/phase6_report.py` from accepted decisions and explicit analysis assumptions. '
             'The student-facing syllabus is frozen; Phase 6 is closed. These detailed schedules and workload assumptions are internal planning views, '
             'not additional syllabus commitments. Calendar weeks are assessment targets; week.slot labels identify logical teaching sessions. '
             'Actual-date checks remain deferred until after Phase 7.')
    def report(title, *parts):
        return '\n\n'.join(['# '+title, intro, *parts])+'\n'
    assignment_table = table(['Assignment','Last logical prerequisite','Release target','Deadline target'],
                             [[r['id'], label(r['last_session']),r['release'],r['deadline']] for r in schedule])
    calendar_note = ('Release each assignment immediately after all its prerequisites are taught and retain at least 21 elapsed days. '
                     'Accepted week targets do not prove that this is possible. A1 due early Week 7 requires reconciliation with the actual Week 4 teaching/makeup dates. '
                     'A1/A2 and A2/A3 may overlap by one week; exact overlap lengths remain unverified.')
    envelope = (f'{len(sessions)} lectures retained; one makeup each in October, November and December, all unbooked. '
                'Semester starts the week of October 5, 2026, with an expected January 8, 2027 end. '
                'October 29 and November 3 affect availability; December 31 is assumed unavailable for planning, not claimed as an official holiday. '
                'January instructor unavailability requires feasible teaching/grading arrangements. Do not equate the 13 logical teaching weeks with 14 calendar weeks.')
    exam_rows = []
    for e in grading['midterms']:
        assert set(e['coverage_sessions']) <= by_id.keys()
        exam_rows.append([e['id'], 'Week '+', '.join(map(str,e['window_weeks'])), e['scope']])
    e3 = grading['third_midterm']['current_semester_alternative']
    assert set(e3['coverage_sessions']) <= by_id.keys()
    exam_rows.append(['midterm_3','Week '+str(e3['week']),grading['third_midterm']['clarification']])
    exams = table(['Exam','Calendar target','Coverage in logical teaching sequence'], exam_rows)
    pressure = ('- Weeks 6–7: MT1 is Week 6; A1/A2 overlap, then A1 early Week 7 and project design later that week.\n'
                '- Weeks 8–9: A2/A3 overlap alongside dense policy teaching; A2 is due Week 9.\n'
                '- Weeks 10–11: MT2 is Week 10; progress is early Week 11 and A3 later that week. Separation within Week 11 needs actual dates.\n'
                '- Week 12: A4 opens after offline prerequisites; LLM video preparation may add workload near this period, depending on lecture mapping.\n'
                '- Weeks 13–14: MT3 is Week 13; online presentations are Week 14. The former same-week conflict is removed, but staffing is unresolved.\n'
                '- Weeks 15–16: A4 then the project report. The report must remain one week before letter grades; dates and grading turnaround are unverified.')
    assessment = report('Assessment schedule', assignment_table, calendar_note, envelope,
                        '## Exams', exams,
                        'Each exam is 15%, uses a separate slot and has an unbooked date/duration. No final exam. '
                        'Coverage must have been taught with preparation time; homework submission or graded feedback is not an exam prerequisite. '
                        'MT3 includes the bounded conceptual CQL question and excludes the LLM bridge.',
                        '## Deadline pressure', pressure)
    project_table = table(['Milestone','Calendar target','Course grade','Length'],
                          [[m['name'],milestone_when(m),f'{number(m["weight_percent"])}%',m['length']] for m in project['milestones']])
    for m in project['milestones']:
        assert set(m['prerequisites']) <= by_id.keys()
    pp = project['presentation_plan']
    used = pp['teams_per_slot']*(pp['talk_minutes']+pp['discussion_minutes'])
    assert used <= pp['slot_minutes']
    project_view = report('Project schedule', project_table,
                          'Teams of 2–3 encouraged; individual/four-person teams considered case by case.',
                          pp['delivery']+'. '+pp['attendance']+' '+pp['peer_grading'],
                          f'{pp["slot_count"]} tentative {pp["slot_minutes"]}-minute slots, up to {pp["teams_per_slot"]} teams each. '
                          f'{used} minutes of presentations/discussion leave {pp["slot_minutes"]-used} for transitions per slot. '
                          'TA staffing and final team slots remain unconfirmed; do not assume the instructor can substitute in January.',
                          project['advanced_track'], 'Final report dates and grading turnaround will be checked after Phase 7 against the official letter-grade deadline.')
    video_est = read('analysis/phase3_proposal.yaml')['videos']
    video_rows = []
    for v in videos['videos']:
        assert v['before'] in by_id
        e = next(x for x in video_est if x['id']==v['id'])
        video_rows.append([v['id'],f'{videos["release_policy"]["lead_days"]} days before use',label(v['before']),
                           f'{e["playback_minutes"][0]}–{e["playback_minutes"][1]}',f'{e["student_effort_minutes"][0]}–{e["student_effort_minutes"][1]}'])
    video_table = table(['Video','Tentative release rule','Before logical session','Playback minutes','Total study minutes'],video_rows)
    delivery = report('Video and reading plan',video_table,
                      'The seven-day lead is a rule, not a verified release date. On uninterrupted logical weeks it corresponds to 9.1 and 12.1; actual calendar placement remains pending.',
                      table(['Checkpoint week','Action'],[[c['week'],c['action']] for c in videos['checkpoints']]),
                      'No student readings are assigned. The internal reference map creates no reading-only exam requirement. No third policy video is required by default.')
    estimates = read('analysis/phase5_plan.yaml')['project']
    hours = lambda items,key: [sum(x[key][i] for x in items) for i in (0,1)]
    ah = hours(tasks,'hours'); ph = hours(estimates['milestones'],'student_hours')
    subsets = list(combinations(tasks,policy['aggregation']['counted_count']))
    three = [min(sum(a['hours'][0] for a in c) for c in subsets), max(sum(a['hours'][1] for a in c) for c in subsets)]
    vh = [x/60 for x in hours(video_est,'student_effort_minutes')]
    contact = len(sessions)*cfg['course']['lecture_minutes']/60
    attendance = pp['slot_minutes']/60
    a = review['workload_assumptions']; count = len(exam_rows)
    prep = [count*x for x in a['exam_preparation_hours_per_midterm']]
    sitting = [count*x for x in a['exam_duration_hours_each']]
    routine = [cfg['course']['planned_weeks']*x for x in a['routine_study_hours_per_teaching_week']]
    total = [contact+ah[i]+ph[i]+vh[i]+attendance+prep[i]+sitting[i]+routine[i] for i in (0,1)]
    total3 = [total[i]-ah[i]+three[i] for i in (0,1)]
    span = lambda x: number(x[0])+'–'+number(x[1])
    syllabus_review = check_content(cfg, policy, grading, project)
    workload = report('Phase 6 workload audit',
        '**Result: conditionally feasible, not a demonstrated fit to the target.** The instructor accepts workload in principle against '
        +span(calendar['workload_review']['target_total_student_hours'])+' hours. Unpiloted ranges extend above that target; preserve them until task pilots supply evidence.',
        table(['Component','Student hours','Basis'],[
            ['Lectures',number(contact),'All 26 × 70 minutes; includes buffer and administration'],
            ['All four assignments',span(ah),'Estimated active effort, including writeup/disclosure'],
            ['Exactly three assignments',span(three),'Alternative to all four; selection-dependent'],
            ['Project work',span(ph),'Non-overlapping milestone effort, including final report and talk preparation'],
            ['Presentation attendance',number(attendance),'Own slot, including own talk; no double counting'],
            ['Video study',span(vh),'Playback plus pause/review'],['Assigned reading','0','No student readings'],
            ['Exam sittings',span(sitting),'Assumed durations; unconfirmed'],['Exam preparation',span(prep),'Dedicated preparation only'],
            ['Routine study',span(routine),'Excludes all other listed work']]),
        f'**Total: {span(total)} hours with all four assignments; {span(total3)} with exactly three.** '
        'Best-three grading may induce four attempts. These are sensitivity ranges, not observed workload; unattended compute and exceptional troubleshooting are excluded. '+a['confidence'],
        '## Deadline concentration', pressure,
        'Illustrative overlap scenario: A2 and A3 each require about 3.3–4.7 active hours per week over three weeks. '
        'Together with 4–6 project hours, 2⅓ contact hours and 2–4 routine-study hours, an overlap week can reach about 15–22 hours before exam preparation or videos. '
        'This is an uneven-work scenario, not a measured weekly estimate. Required video study is '+span(vh)+' hours across the two units.',
        '## Staffing and delivery',envelope,
        f'Presentations require {pp["slot_count"]*pp["slot_minutes"]/60:g} scheduled TA hours across all slots, plus setup, moderation and grading. '
        f'Students attend {attendance:g} hours each. Team count, TA availability and TA/group grade aggregation are unresolved. '
        'The accepted presentation arrangement is therefore a staffing dependency, not a confirmed staffed event.',
        analysis['staffing_audit']['confidence']+' '+analysis['staffing_audit']['risk'],
        'Scaffolds, tests, fixed run budgets and shared answer guides must be piloted before release. No pilot or grading-capacity calibration is claimed complete. '
        'January A4 and project grading need identified staff and turnaround time.',
        'The supplied syllabus permits remaining late days for the final report, with a possible Incomplete grade. This can consume or exceed the one-week grading buffer. '
        'Operational handling and the unspecified excess-lateness penalty remain open; this audit does not revise either policy.',
        '## Live teaching budget',
        f'{live[0]} teaching + {live[1]} additional administration minutes, leaving {number(live[2])} usable minutes. '
        'The separate 15% buffer and configured 20-minute syllabus briefing are not counted twice. No exam/presentation time consumes lectures. '
        'Per-session capacity and prerequisite order pass existing curriculum checks; policy-gradient/GAE/PPO and offline units remain conceptually dense. '
        'Their small local margins cannot be treated as freely transferable semester slack. See the curriculum and time audits.',
        '## Follow-up',
        'Calendar mapping, 21-day and exam preparation intervals, presentation staffing and grade-deadline compatibility are deferred until after Phase 7. '
        'Concrete assignment pilots and rubric/example work remain deferred until implementation before release. No curriculum expansion or workload reduction is inferred.')
    consistency = report('Phase 6 course-design consistency audit',
        '**Syllabus frozen by instructor acceptance; Phase 6 closed.** Internal date-dependent checks remain pending. '
        'Freeze scope and artifact identity are recorded in `decisions/syllabus_decisions.yaml`.',
        table(['Check','Result','Evidence or limitation'],[
            ['Teaching scope and time','Pass unchanged','Exact comparison with the start-of-Phase-6 baseline; per-session and total budget checks pass.'],
            ['Learning outcomes and Core depth','Supported with pacing qualifications','Existing curriculum outcome mapping and worked Core activities validated; see curriculum consistency audit.'],
            ['Assessment alignment','Supported with accepted limitation','Assignment audit covers all Core groups. Best-three permits missing implementation evidence; exams do not establish coding mastery.'],
            ['Assignment windows','Pending actual dates',calendar_note],
            ['Exams','Coverage defined; timing pending','MT1 Week 6, MT2 Week 10, MT3 Week 13. Topic IDs checked; taught-before-exam and preparation intervals require calendar mapping.'],
            ['Projects','Sequence plausible; dates pending','Design after DQN; progress after policy teaching in logical sequence. Advanced tracks need early self-study and a simple baseline.'],
            ['Presentation','Week-level conflict removed','Week 14 follows MT3 Week 13; TA staffing, slots and TA/group grading details remain unresolved.'],
            ['Final report','Pending grade deadline','Week 16 target remains subject to one week before letter grades and feasible grading turnaround.'],
            ['Video prerequisites','Rules checked; dates pending','Two required units; seven-day tentative lead and Weeks 4/8/11 checkpoints. No release dates verified.'],
            ['Readings','Pass','No assigned readings or reading-only exam dependencies.'],
            ['Grading','Pass','45/35/20 totals 100; 15 each per midterm; project weights total 35; best-three normalized to 20.'],
            ['Workload','Accepted in principle; calibration needed',f'{span(total)} all-four / {span(total3)} exactly-three hours; ranges exceed target at the upper end.'],
            ['Syllabus artifact','Frozen identity and published facts checked','Final DOCX/PDF fingerprints match acceptance; Markdown mirrors the concise final DOCX. Historical draft visual review is not evidence of final-file layout.']]),
        'The syllabus preserves instructor discretion on assignment count and timing. Detailed targets remain internal, including assignment windows, '
        'project lengths/dates and video release rules. If assignment count changes, revisit aggregation, alignment and workload. '
        'Operational unknowns remain explicit after freeze. No Phase 7 work has begun.',
        'See [workload](workload.md), [assignment alignment](assignment_alignment.md), [curriculum consistency](curriculum_consistency.md), '
        '[assessment timeline](../assessment_timeline.md) and [syllabus verification](syllabus_verification.md).')
    outputs = {'output/assessment_timeline.md':timeline(), 'output/assessment_schedule.md':assessment,
            'output/project_schedule.md':project_view,'output/video_plan.md':delivery,
            'output/audits/workload.md':workload,'output/audits/design_consistency.md':consistency,
            'output/lecture_plan.md':curriculum_views['output/lecture_plan.md'],
            'output/audits/curriculum_consistency.md':curriculum_views['output/audits/curriculum_consistency.md']}
    outputs['analysis/phase5_completion.md'] = report('Phase 5 completion',
        '**High-level assessment/project/reading design complete by instructor acceptance.**',
        '- Four individual assignments, best-three aggregation, task scope and bounded Double DQN/IQL implementation are accepted.\n'
        '- Project purpose, milestone scope/weights/lengths, team policy and deadline rules are accepted. Current week targets and presentation delivery come from decisions.\n'
        '- No student readings are assigned; two prerequisite videos remain required.\n'
        '- Rubric/penalty details, the example LLM-use report and task pilots remain deferred until implementation before release.\n'
        '- Concrete scaffolds, grading capacity and observed student workload have not been validated by implementation.',
        'The instructor has frozen the final syllabus and closed Phase 6. Actual-date calendar mapping and operational finalization remain after Phase 7. '
        'See `analysis/phase6_handoff.md` and the current workload/design audits for limitations retained after freeze.')
    assert (ROOT/'output/syllabus.md').read_text() == syllabus_markdown(), 'Run syllabus_report.py to refresh the final DOCX view'
    outputs['output/audits/syllabus_verification.md'] = report('Syllabus verification',
        '**Pass for frozen-artifact identity, published-fact checks and Markdown consistency.** Final calendar and operational checks remain deferred.',
        '## Checks', '\n'.join('- '+x for x in syllabus_review['checks']),
        '## Acceptance and review scope',
        'Instructor acceptance and exact DOCX/PDF fingerprints are recorded in `decisions/syllabus_decisions.yaml` and the decision log. '
        'The final files are unchanged. These checks establish identity and text consistency, not a new visual review or upload verification. '
        '`analysis/syllabus_verification.json` is explicitly historical evidence for the earlier detailed draft; it does not certify the final files.',
        'The exporter preserves the final wording, including the repeated disclosure sentence in the LLM policy. It does not apply new editorial corrections.',
        '## Remaining limitations',
        'Exact dates, assignment windows, exam preparation intervals, staffing, final-report grading turnaround and workload calibration remain open. '
        'The syllabus omits detailed internal schedules, project lengths, mandatory-video counts/leads and LLM-report contents; absence is not treated as a failed check or cancellation of internal decisions.')
    return outputs


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    for name,content in build().items():
        path=ROOT/name
        if args.check:
            assert path.exists() and path.read_text()==content, f'Stale generated file: {name}'
        else:
            path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
    print('Frozen syllabus and internal design checked; calendar-dependent checks pending. No syllabus file written.')


if __name__=='__main__':
    main()
