#!/usr/bin/env python3
"""Validate Phase 1 inventories and render factual summaries. No network access.

Usage: python3 scripts/phase1_report.py [--check-only]
All generated reports stay in analysis/source_summaries, permitted in Phase 1.
"""
import argparse
import hashlib
import json
from collections import Counter
from pathlib import Path
from urllib.parse import urlsplit
import yaml

ROOT=Path(__file__).resolve().parents[1]


class UniqueLoader(yaml.SafeLoader):
    pass


def unique_mapping(loader,node,deep=False):
    result={}
    for k,v in node.value:
        key=loader.construct_object(k,deep=deep)
        if key in result:raise ValueError(f'Duplicate YAML key: {key}')
        result[key]=loader.construct_object(v,deep=deep)
    return result


UniqueLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,unique_mapping)


def load(path):
    return yaml.load(path.read_text(),Loader=UniqueLoader)


def validate():
    config=load(ROOT/'config/sources.yaml');inventories=[]
    for src in config['sources']:
        sid=src['id'];path=ROOT/'sources'/sid/'manifest.yaml';m=load(path)
        assert m['source_id']==sid and m['phase']==1
        assert m['offering']['label'] and m['offering']['evidence']
        ids=[r['id'] for r in m['materials']];assert len(ids)==len(set(ids)),sid
        for r in m['materials']:
            for key in ['id','title','material_type','instructional_use','offering','storage','observed_at','provenance','accessibility']:
                assert key in r,(sid,r['id'],key)
            assert r['provenance'],(sid,r['id'])
            assert not set(r)&{'topic_id','mastery','pedagogical_role','accepted'},(sid,r['id'])
            if 'path' in r:
                p=ROOT/r['path'];assert p.is_file(),p
                assert hashlib.sha256(p.read_bytes()).hexdigest()==r['sha256'],p
            if 'url' in r:assert urlsplit(r['url']).scheme in ['http','https'],r['url']
            for e in r['provenance']:
                for key in ['path','index_path','inventory_path','inspection_path']:
                    if key in e:assert (ROOT/e[key]).is_file(),e[key]
        raw=ROOT/'sources'/sid/'snapshots/local_inventory.json'
        if raw.exists():
            paths={x['path'] for x in json.loads(raw.read_text())['files']}
            assert paths=={x['path'] for x in m['materials'] if 'path'in x},sid
        for p in (ROOT/'sources'/sid/'snapshots').glob('*.json'):json.loads(p.read_text())
        inventories.append(m)
    assert not (ROOT/'sources/rl_book/manifest.yaml').exists(),'Book must not require a manifest'
    assert not (ROOT/'analysis/normalized_topics.yaml').exists(),'Phase 2 must not have begun'
    # This phase began with a hash snapshot of normally read-only project files.
    protected=Path('/private/tmp/rl_phase1_protected.json')
    if protected.exists():
        for p,digest in json.loads(protected.read_text()).items():
            assert hashlib.sha256((ROOT/p).read_bytes()).hexdigest()==digest,('normally read-only file changed',p)
    for p in (ROOT/'config').glob('*.yaml'):load(p)
    return inventories


def link(text,url):
    return '['+text.replace('|','\\|').replace('[','(').replace(']',')')+'](<'+url+'>)'


def render(m):
    sid=m['source_id'];counts=Counter(x['material_type'] for x in m['materials'])
    lines=[f'# {sid} — Phase 1 source inventory','',
        'Generated by `scripts/phase1_report.py` from the source manifest. This is factual inventory, not a curriculum comparison.', '',
        f'- Offering: {m["offering"]["label"]}.',
        f'- Manifest: [manifest.yaml](../../sources/{sid}/manifest.yaml).',
        '- Provenance and accessibility: see per-material manifest entries and `snapshots/` indexes.',
        '- Timestamps are UTC inspection/retrieval times; unknown original local download dates remain unknown.', '',
        '## Inventory counts','', '| Material type | Records |','| --- | ---: |']
    lines += [f'| {k} | {v} |' for k,v in sorted(counts.items())]
    lines+=['','Counts represent files, links, or embedded references, not teaching hours or distinct topics. Slide variants and exam solutions remain separate artifacts.','','## Source observations','']
    for obs in m['observations']:
        lines.append('- '+obs['statement']+' Evidence: '+ '; '.join(obs['evidence'])+'.')
    lines+=['','## Evidence gaps and limits','']
    for gap in m['evidence_gaps']:lines.append('- **'+gap['category']+'**: '+gap['description'])
    failures=[x for x in m['materials'] if x['accessibility']['status'] in ['http_error','transport_error','not_fetched_robots_policy','not_fetched_redirect_policy']]
    for x in failures:lines.append('- **Link access**: '+x['title']+' — '+str(x['accessibility']))
    lines+=['','Missing or inaccessible evidence does not establish that material was not taught. Scheduled/listed slides do not verify what was delivered live. Public HTTP availability does not establish code executability or recording playback.','','## Material index','',
            '| Material | Type | Source use | Availability |','| --- | --- | --- | --- |']
    for r in m['materials']:
        url=r.get('url') or ('../../'+r['path'] if r.get('path') else '../../sources/'+sid+'/manifest.yaml')
        lines.append('| '+link(r['title'],url)+' | '+r['material_type']+' | '+r['instructional_use']+' | '+r['accessibility']['status']+' |')
    lines+=['','## Phase boundary','', 'This source can enter Phase 2 with the limitations above. No topic equivalences, depth ratings, book-topic mappings, or redesigned-course decisions have been produced.','']
    out=ROOT/'analysis/source_summaries'/f'{sid}.md';out.parent.mkdir(parents=True,exist_ok=True);out.write_text('\n'.join(lines))
    (ROOT/'sources'/sid/'README.md').write_text(f'''# {sid}

Phase 1 inventory for **{m['offering']['label']}**.

- [Manifest](manifest.yaml): material records, source-specific observations, and evidence gaps.
- [Source summary](../../analysis/source_summaries/{sid}.md): generated human-readable inventory.
- `snapshots/`: link catalogs, inspection metadata, local file hashes, and HTTP checks.

Existing local teaching files remain in place. Remote materials are linked; selected assignment/project PDFs were inspected temporarily, not mirrored here. Page snapshots retain catalog metadata, links and source context rather than complete websites.

`observed_at` records when evidence was inspected. An unknown original local download date is not replaced with that date. `instructional_use` describes the source's use, not a role or delivery decision for the redesigned course. `listed_teaching` and `scheduled_teaching` do not assert confirmed live delivery. `additional_material_requirement_unspecified` preserves an unclear reading requirement. Lecture order/labels are source-local only.

HTTP metadata checks, PDF text inspection, and linked-but-unchecked resources are labeled separately. Starter code is inventoried, not executed. Detailed provenance lives in the manifest and indexes. The book is a direct reference file and has no manifest.

For collection and regeneration commands, see [the Phase 1 collection guide](../../scripts/README.md).
''')


def completion(inventories):
    lines=['# Phase 1 completion report','',
        'Generated by `scripts/phase1_report.py`. Phase 1 is complete with documented evidence gaps. No blocking dependency remains for the inventory exit criteria. Phase 2 has not begun.','',
        '## Exit criteria','',
        '| Criterion | Result | Evidence |','| --- | --- | --- |',
        '| Configured course sources inventoried | Pass | Seven manifests and seven source summaries; local-file inventories account for all supplied non-generated files. |',
        '| Offering/year identified where practical | Pass | Course-page headings and PDF evidence; composite local baseline; original local download dates left unknown. |',
        '| Inaccessible or ambiguous resources documented | Pass | Per-source gaps, per-material accessibility, and dated HTTP/PDF inspection records. |',
        '| Major evidence gaps identified | Pass | Recording access, absent assessment artifacts, incomplete provenance, and conflicting source dates are recorded below. |',
        '| Provenance sufficient for Phase 2 | Pass | Source URLs or existing file paths, source-context locators, timestamps, material types, and local/PDF hashes where inspected. |','',
        'The registered book is intentionally excluded from course manifests. Course-to-book mapping remains Phase 2 work.','',
        '## Inventories','', '| Source | Offering | Material records | Summary |','| --- | --- | ---: | --- |']
    for m in inventories:lines.append(f'| {m["source_id"]} | {m["offering"]["label"]} | {len(m["materials"])} | [Summary]({m["source_id"]}.md) |')
    lines+=['','## Blockers and evidence gaps','', 'No blocker prevents completing Phase 1. The following limitations remain visible for subsequent evidence use:','']
    for m in inventories:
        lines+=['### '+m['source_id'],'']
        lines += ['- '+g['description'] for g in m['evidence_gaps']]
        lines+=['']
    checks=[]
    for m in inventories:
        p=ROOT/'sources'/m['source_id']/'snapshots/link_checks.json'
        if p.exists():checks+=json.loads(p.read_text())
    status=Counter(x['status'] for x in checks)
    lines+=['## Verification','',
        f'- {len(inventories)} manifests validated for unique material IDs, required fields, configured source identity, and provenance-file existence.',
        '- All inventoried local files still match their recorded SHA-256 hashes.',
        '- Local-file catalog completeness and all configuration YAML parsing checked.',
        f'- {len(checks)} distinct URLs checked within their source inventories: '+', '.join(f'{v} {k}' for k,v in sorted(status.items()))+'.',
        '- HTTP checks are metadata checks; selected assignment and project PDFs additionally received text inspection. Recording playback, linked optional papers, code execution and individual student-project report contents were not systematically reviewed.',
        '- The Spring 2026 CS224R project-report gallery is indexed as a collection; individual titles/URLs remain in its catalog snapshot.',
        '- No changes to configuration, accepted decisions, governance, teaching artifacts, or output files were needed for Phase 1.','',
        '## Recommended next actions','',
        'Review any source ambiguities that matter to later analysis. Additional inaccessible artifacts may be supplied later; their absence must remain unknown rather than become negative coverage evidence. Phase 2 may be requested separately using these inventories, retaining all evidence limitations. Stop here until that request.','']
    (ROOT/'analysis/source_summaries/phase1_completion.md').write_text('\n'.join(lines))
    (ROOT/'analysis/source_summaries/README.md').write_text('# Phase 1 source inventories\n\nStart with the [completion report](phase1_completion.md) for exit criteria, verification, gaps, and links to every source summary.\n\nThese generated reports describe source evidence only. Regenerate with `python3 scripts/phase1_report.py`; see `scripts/README.md` for collection details.\n')


if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check-only',action='store_true');args=p.parse_args()
    inventories=validate()
    if not args.check_only:
        for m in inventories:render(m)
        completion(inventories)
    print(f'Validated {len(inventories)} manifests, {sum(len(m["materials"]) for m in inventories)} material records; '+('no writes.' if args.check_only else 'reports rendered.'))
