#!/usr/bin/env python3
"""Render the first Phase 5 grading/project/reading review; does not accept proposals."""
import argparse
import re
import yaml
from phase3_audit import ROOT, read, table, number, build as time_audit


def decision(name):
    blocks=re.findall(r'```yaml\n(.*?)\n```',(ROOT/f'decisions/{name}_decisions.md').read_text(),re.S)
    assert len(blocks)==1
    return yaml.safe_load(blocks[0])


def build():
    _,totals=time_audit()
    p=read('analysis/phase5_plan.yaml'); d=read('decisions/topic_decisions.yaml'); cfg=read('config/course.yaml')
    grading=decision('grading'); project_decision=decision('project'); reading_decision=decision('reading'); assignment=decision('assignment')
    assert d['curriculum_state']=='frozen'
    sessions={s['id']:s for s in d['lecture_plan']}
    labels={k:f'{s["week"]}.{s["slot"]}' for k,s in sessions.items()}
    assert sum(grading['categories_percent'].values())==100
    accepted_milestones={m['id']:m for m in project_decision['milestones']}
    milestones=[{**m,**accepted_milestones[m['accepted_milestone_ref']]} for m in p['project']['milestones']]
    presentation=project_decision['presentation_plan']
    slot_used=presentation['teams_per_slot']*(presentation['talk_minutes']+presentation['discussion_minutes'])
    assert slot_used<=presentation['slot_minutes']
    assert presentation['expected_max_teams']<=presentation['slot_count']*presentation['teams_per_slot']
    assert sum(m['weight_percent'] for m in milestones)==grading['categories_percent']['project']
    assert [m['id'] for m in milestones]==project_decision['accepted_structure']
    for m in milestones:
        assert all(sessions[k]['week']<=m.get('week',cfg['course']['planned_weeks']) for k in m['prerequisites']),m['id']
        assert len(m['student_hours'])==2 and 0<=m['student_hours'][0]<=m['student_hours'][1]
    for exam in grading['midterms']:
        assert set(exam['coverage_sessions'])<=sessions.keys()
        assert max(sessions[k]['week'] for k in exam['coverage_sessions'])<min(exam['window_weeks'])
    assert set(grading['third_midterm']['future_template']['coverage_sessions'])<=sessions.keys()
    n={t['id']:t for t in read('analysis/normalized_topics.yaml')['topics']}
    refs={}
    for t in n.values():
        for r in t.get('book_mapping',{}).get('rl_book',{}).get('references',[]):
            refs[str(r['section'])]=r
    for w in p['readings']['weekly_sections']:
        assert set(w['sections'])<=refs.keys()
    assert {w['week'] for w in p['readings']['weekly_sections']}==set(range(1,cfg['course']['planned_weeks']+1))
    total_hours=[sum(m['student_hours'][i] for m in milestones) for i in (0,1)]
    header='Generated by `python3 scripts/phase5_report.py` from accepted decisions, [Phase 5 analysis](../analysis/phase5_plan.yaml), frozen curriculum and existing normalized evidence. **Project milestone weights, lengths, deadline rules and team policy are accepted; workload estimates remain analysis. Phase 5 high-level design is accepted; Phase 6 integration is in progress.**'
    project=['# Project structure and curriculum alignment','',header,'',
             'Retain the five existing milestone types. Overall project weight comes from [grading decisions](../decisions/grading_decisions.md); the split below is accepted. All percentages are of the total course grade.','',
             table(['Milestone','Accepted deadline','Course weight','Length','Purpose / evidence'],[[m['name'],('Week '+str(m['week']) if 'week' in m else m['deadline_rule']),f'{number(m["weight_percent"])}%',m['length'],m['scope']+' '+m['evidence']] for m in milestones]),'',
             p['project']['timing_note']+' '+accepted_milestones['final_report']['expected_window'],'','## Prerequisite and workload check','',
             table(['Milestone','Already-taught supporting sessions','Estimated active hours per student'],[[m['name'],', '.join(labels[k] for k in m['prerequisites']),f'{m["student_hours"][0]}–{m["student_hours"][1]}'] for m in milestones]),'',
             f'Total estimated project active work: **{total_hours[0]}–{total_hours[1]} hours per student**. '+p['project']['workload_confidence'],'',f'Presentation attendance: {presentation["slot_minutes"]} minutes per student including their own presentation. The instructor plans {presentation["slot_count"]} slots for up to {presentation["expected_max_teams"]} teams; {slot_used} minutes used per slot leaves {presentation["slot_minutes"]-slot_used} for transitions. '+presentation['finalization_trigger']+' '+presentation['schedule_conflict']+' Peer grading: '+presentation['peer_grading'],'',
             'Project design remains in Week 7 and progress in Week 10. Midterm windows remain Weeks 6/7 and 10/11; the instructor chose extending assignment deadlines instead of moving exams. Exact exam dates remain unbooked; see the combined timeline.','',
             '## Scope and evaluation','','Teams of '+ '–'.join(str(x) for x in project_decision['team_size']['encouraged'])+' are encouraged. Individual work and four-person teams are decided case by case.','',
             'Suitable bounded project types: '+ '; '.join(project_decision['accepted_types'])+'.','',
             project_decision['advanced_track'],'',project_decision['evaluation'],'',project_decision['grading_principle'],'',p['project']['llm_policy'],'',
             '**Displacement:** '+p['project']['displacement'],'',
             '## Evidence for retaining this structure','',
             '- Local [Project.pdf](../sources/current_course/Project.pdf#page=3), pp. 3–4 and 8–11, already connects problem choice, implementation, baselines and reporting; p. 11 permits individual work or teams up to three with scaled expectations. The current instructor policy supersedes the old default: teams of 2–3 encouraged, with individual/four-person exceptions case by case.',
             '- Local [proposal instructions](../sources/current_course/ProposalSpring21.pdf#page=1) specify formulation and evaluation early; [progress instructions](../sources/current_course/ProgressAndPlanSpring2021.pdf#page=1) permit reusing unchanged sections and request baseline/implementation progress.',
             '- Local [final report](../sources/current_course/FinalSpring25.pdf#page=1), pp. 1–2, specifies baseline, evaluation, interpretation, a six-page limit and LLM disclosure examples. These support the proposed operational details; the accepted two-page proposal and 6–8-page final report supersede the old lengths.',
             '- The inventoried [CS234 Winter 2026 project](https://web.stanford.edu/class/cs234/project.html) uses proposal/milestone/final-report progression, reproducibility details and contribution statements (stored evidence: `sources/stanford_cs234/snapshots/project_index.json`, Project Milestone / Final Report Submission). Its report lengths and workload are not copied.',
             '- The inspected [CS285 Spring 2026 outline](https://rail.eecs.berkeley.edu/deeprlcourse/static/misc/final_project_outline.pdf), p. 1, frames project work as implementation, evaluation and analysis. This is a reference format, not a requirement for novelty or a graduate-scale research project.','',
             '## Decisions still needed','',*('- '+x for x in p['project']['open_items']),'']
    def booklink(r):
        return f'[§{r["section"]}: {r["section_title"]}](../sources/RLbook2020.pdf#page={r["pdf_pages"][0]}) (printed pp. {r["printed_pages"][0]}–{r["printed_pages"][1]})'
    readings=['# Book-first reading map','',header,'',
              '**Internal candidate map. No readings are assigned by this document.** '+reading_decision['publication_choice']+'. The required prerequisite videos remain separate.','',
              p['readings']['strategy_recommendation'],'',p['readings']['exam_recommendation'],'',
              '## Weekly book menu','',
              'References come directly from `analysis/normalized_topics.yaml`, using the configured Sutton–Barto book. Printed pages and PDF pages differ by 22; links use PDF pages. This is a menu of relevant sections, not a requirement to read whole chapters or every listed page.','',
              table(['Week','Mapped book selections','Scope limit'],[[w['week'],'; '.join(booklink(refs[k]) for k in w['sections']) or 'No direct selection',w['note']] for w in p['readings']['weekly_sections']]),'',
              '**Workload:** No required reading minutes currently assigned. '+p['readings']['optional_effort'],'',
              '## Selective companions for book gaps','',p['readings']['candidate_state'],'',
              'These are previously inspected teaching excerpts, not evidence that the reference course assigned them as readings. Named paper pointers below are separately labeled. No broad web search or current-method survey was performed.','']
    rows=[]
    for c in p['readings']['supplement_candidates']:
        e=n[c['topic_id']]['sources'][c['source']]['evidence'][c['evidence_index']]
        assert e['evidence_kind']=='teaching'
        link=e.get('url') or '../'+e['path']
        pages=e.get('pdf_pages',[])
        if pages:link+='#page='+str(pages[0])
        rows.append([n[c['topic_id']]['name'],f'[{c["source"]}]({link}), PDF pp. {pages[0]}–{pages[1]}',c['recommendation']])
    readings += [table(['Topic','Existing source excerpt','Proposed use / qualification'],rows),'',
                 '## Already-indexed seminal paper pointers','',
                 'For DQN, PPO and IQL, the existing evidence explicitly records optional CS224R references. These are provenance-backed candidates, not a newly approved reading list or an ease rating. Full-paper reading is not needed to deliver the frozen course.','']
    for tid in ('dqn','proximal_policy_optimization','implicit_q_learning'):
        obs=n[tid]['sources']['stanford_cs224r']
        for e in obs['evidence']:
            if e['evidence_kind']=='reading_pointer' and e.get('url'):
                readings += [f'- [{n[tid]["name"]} paper]({e["url"]}) — {e["claim"]}']
    readings += ['', 'Recent replacements, surveys, full SAC/CQL paper selection and LLM paper updates are deferred. For CQL’s five-minute exposure, the live contrast is sufficient; any new reading would need its own accessibility check.','',
                 '## Topic-level book mapping','',
                 'Direct and related-background relations are preserved. No direct mapping established does not mean the book has no related material. Optional-extension-only topics are excluded from this required-scope index.','']
    rows=[]
    for g in d['scope_decisions']:
        if g['role']=='extension':continue
        for tid in g['topic_ids']:
            mapping=n[tid].get('book_mapping',{}).get('rl_book',{})
            rows.append([n[tid]['name'],'; '.join(booklink(r)+' — '+r['relationship'] for r in mapping.get('references',[])) or 'No direct mapping established',mapping.get('note','')])
    readings += [table(['Topic','Book reference / relationship','Qualification'],rows),'']
    weights=grading['categories_percent'];spare=totals[2];loss=cfg['course']['lecture_minutes']*cfg['design']['planned_content_fraction']
    audit=['# Phase 5 first review: grading, project and readings','',
           'Generated by `python3 scripts/phase5_report.py`. Curriculum is frozen with accepted bounded implementation revisions; Phase 5 design is accepted. This is not the final workload audit.','',
           '## Accepted grading envelope','',
           table(['Category','Course grade'],[[k.title(),f'{v}%'] for k,v in weights.items()]),'',
           'Category weights total 100%; the accepted project milestone split totals its 35% category. Individual assignment design is accepted under best-three-of-four grading; timing is integrated in Phase 6.','',
           '## Exam scope and remaining date choices','',
           table(['Exam','Window','Coverage'],[[e['id'],str(e['window_weeks']),e['scope']] for e in grading['midterms']]),'',
           '**Third midterm:** '+grading['third_midterm']['clarification'],'',
           'Future template: Week 14, 9.2 through Week 13 including the LLM bridge. Accepted current-semester schedule: Week 13, 9.2 through Week 12, excluding the LLM bridge. Week 14 is outside the 13-week teaching plan and is only a possible exam/submission period; confirm the official calendar.','',
           p['grading_review']['exam_weights_proposal'],'',
           '## Teaching-time result and schedule sensitivity','',
           'The instructor confirmed separate exam slots. The frozen teaching allocation is unchanged; exam attendance and preparation add out-of-class student workload, with durations still to be specified. The following scenarios assume each exam replaces one ordinary 70-minute lecture, with no replacement teaching; they are not accepted schedule changes.','',
           table(['Replacement lectures','Usable teaching capacity lost','Deficit beyond existing usable margin'],[[k,number(k*loss),number(max(0,k*loss-spare))] for k in (0,1,2,3)]),'',
           f'Base unallocated usable margin: {number(spare)} minutes. Even a semester-wide arithmetic fit may fail locally. Exams in normal lectures would require a specific curriculum/time revision; the same generic buffer cannot be counted as both exam time and teaching slack. Separate slots are accepted; only exam duration and exact dates remain unresolved.','',
           '## Assessment risks and recommendations','',
           assignment['aggregation']['formula']+'. '+assignment['aggregation']['completion_rule'],'',p['grading_review']['drop_rule_risk'],'',p['grading_review']['llm_operational_recommendation'],'',p['grading_review']['reading_risk'],'',
           'Midterm 3 provides a common conceptual assessment route for bandits, search/model-based RL and offline RL. Its questions must respect the frozen explain/analyze versus Exposure scope, including a brief conceptual CQL contrast. Week 13 LLM exposure is outside this semester’s exam coverage; no mandatory LLM implementation is introduced. Detailed assessment blueprints remain Phase 5 work.','',
           '## Project and reading result','',
           f'Retain the project spine; see [project review](../project.md). Estimated active project work is {total_hours[0]}–{total_hours[1]} hours per student, low confidence, plus presentation attendance. '
           'This excludes assignments, exam preparation and optional reading; it is not the total course workload. Late-topic projects require earlier preparation and a feasible baseline.','',
           'See the [book-first map](../readings.md). It uses existing normalized book references and selective inspected course excerpts; no evidence recollection or broad recent-paper search. Readings are outside current planning; the retained map adds no reading-only exam requirement and is not being expanded.','',
           '## Phase 6 follow-up and in-semester work','',
           '- Confirm per-exam weights, durations and exact dates around milestone deadlines. Third midterm in Week 13 and separate exam slots are accepted.',
           '- Project weights, lengths, team policy and final deadline rule are accepted. Finalize presentation scheduling after proposals and teams freeze; resolve the Week 13 midterm clash during the semester as directed. Operational project disclosure wording remains open.',
           '- Preserve accepted reading deferment this semester; retain the internal map for the next iteration.',
           '- Accepted [assignments](../assignments.md) include integrated Double DQN and scaffolded IQL. Release after prerequisites, allow 21 days, retain original releases, and allow one-week overlaps. Rubric/example work is deferred to the semester.',
           '- Then audit combined assignment/project/exam/video/presentation workload and alignment before syllabus/design freeze. Phase 6 is now in progress.','']
    return {'output/project.md':'\n'.join(project),'output/readings.md':'\n'.join(readings),'output/audits/phase5_initial_review.md':'\n'.join(audit)}


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for name,content in build().items():
        path=ROOT/name
        if args.check:assert path.exists() and path.read_text()==content,f'Stale view: {name}'
        else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
    print('Phase 5 first review valid: grading sums, project weights/prerequisites, reading provenance and generated views checked. Open decisions remain explicit.')


if __name__=='__main__':main()
