#!/usr/bin/env python3
"""Generate Phase 6 syllabus/schedules and workload/consistency audits from accepted design."""
import argparse
from datetime import date, datetime, timedelta
from itertools import combinations
from phase3_audit import ROOT, read, table, number, build as time_audit
from phase5_report import decision
from design_data import assignments, assignment_schedule, when


def build():
    _,live=time_audit()
    cfg=read('config/course.yaml'); curriculum=read('decisions/topic_decisions.yaml'); review=read('analysis/phase6_review.yaml')
    analysis,policy,tasks=assignments(); grading=decision('grading'); project=decision('project'); videos=decision('video'); readings=decision('reading')
    sessions=curriculum['lecture_plan']; by_id={s['id']:s for s in sessions}; schedule=assignment_schedule()
    project_est=read('analysis/phase5_plan.yaml')['project']; video_est=read('analysis/phase3_proposal.yaml')['videos']
    assert curriculum['curriculum_state']=='frozen' and policy['state']=='high-level-design-accepted'
    now=[{k:s[k] for k in ('id','week','slot','title','teaching_minutes','administration_minutes')} for s in sessions]
    assert now==review['weekly_baseline'],'Weekly teaching sequence or minutes changed; instructor must be notified'
    assert sum(grading['categories_percent'].values())==100
    assert sum(m['weight_percent'] for m in project['milestones'])==grading['categories_percent']['project']
    for row in schedule:
        assert row['start']==row['ready'],'Original prerequisite-based release must be retained'
        span=(row['end']-row['start']).days if row['dated'] else (row['end']-row['start'])*7
        assert span==policy['schedule_policy']['duration_days']
    def sl(k):return f'{by_id[k]["week"]}.{by_id[k]["slot"]}'
    def window(m):return 'Week '+str(m['week']) if 'week' in m else m['deadline_rule']+' (expected '+m['expected_window']+')'
    video_rows=[]
    for v in videos['videos']:
        needed=by_id[v['before']];release_week=needed['week']-videos['release_policy']['lead_days']/7
        assert release_week>=1
        e=next(x for x in video_est if x['id']==v['id'])
        calendar=review['calendar']['session_dates']
        release=(date.fromisoformat(calendar[v['before']])-timedelta(days=videos['release_policy']['lead_days'])).isoformat() if v['before'] in calendar else f'{int(release_week)}.{needed["slot"]}'
        video_rows.append([v['id'],release,sl(v['before']),f'{e["playback_minutes"][0]}–{e["playback_minutes"][1]}',f'{e["student_effort_minutes"][0]}–{e["student_effort_minutes"][1]}'])
    assert readings['required_readings']==[] and not grading['final_exam_required']
    intro='Generated by `python3 scripts/phase6_report.py` from accepted decisions and Phase 6 audit assumptions. Relative week.slot labels are planning coordinates, not invented calendar dates.'
    calendar_constraints=read('decisions/schedule_decisions.yaml')
    assert calendar_constraints['accepted_lecture_count']==len(sessions)
    calendar_envelope=('Accepted planning envelope: '+str(calendar_constraints['accepted_lecture_count'])+' lectures, with one tentative November makeup and one December makeup. Instructor reports October 29 holiday, November 3 absence and January unavailability. Start: '+calendar_constraints['semester_start_week_text']+'; expected end '+calendar_constraints['expected_end_text']+'. Exact session dates, makeup placements and year are not inferred. Logical lecture weeks need not equal calendar weeks after these adjustments.')
    calendar_note=('Assignment dates use the supplied teaching calendar and 21 elapsed days.' if all(x['dated'] for x in schedule) else
                   'The relative schedule assumes uninterrupted weeks; holidays, absences and makeups can change the mapping. Week 15.2 is a deadline coordinate after teaching, not an added lecture. A4’s revised January deadline and its proximity to the final project report remain provisional.')
    assignment_table=table(['Assignment','Last prerequisite','Release','Deadline'],[[r['id'],sl(r['last_session']),when(r['start']),when(r['end'])] for r in schedule])
    exam_rows=[[e['id'],'Week '+' or '.join(str(x) for x in e['window_weeks']),e['scope']] for e in grading['midterms']]
    e3=grading['third_midterm'];exam_rows.append(['midterm_3','Week '+str(e3['current_semester_alternative']['week']),e3['clarification']])
    exams=table(['Exam','Accepted window','Coverage'],exam_rows)
    project_table=table(['Milestone','Deadline','Course grade','Length'],[[m['name'],window(m),f'{number(m["weight_percent"])}%',m['length']] for m in project['milestones']])
    # Calendar bands are illustrative, not a substitute for the missing session dates.
    anchor=datetime.strptime(calendar_constraints['semester_start_week_text'].removeprefix('Week of '),'%B %d').date()
    relative={r['id']:((by_id[r['last_session']]['week']-1)+(by_id[r['last_session']]['slot']-1)/2) for r in schedule}
    timeline_rows=[]
    for week in range(4,16):
        releases=[aid+' after '+when(start) for aid,start in relative.items() if int(start)+1==week]
        deadlines=[aid+' at '+when(start+policy['schedule_policy']['duration_days']/7) for aid,start in relative.items() if int(start+policy['schedule_policy']['duration_days']/7)+1==week]
        milestones=[m['name'] for m in project['milestones'] if m.get('week')==week]
        midterms=[e['id'].replace('midterm_','Midterm ')+' (one of Weeks '+' / '.join(map(str,e['window_weeks']))+')' for e in grading['midterms'] if week in e['window_weeks']]
        if week==e3['current_semester_alternative']['week']:midterms.append('Midterm 3')
        if not any((releases,deadlines,milestones,midterms)):continue
        first=anchor+timedelta(weeks=week-1);last=first+timedelta(days=6)
        band=first.strftime('%b %-d')+'–'+last.strftime('%b %-d')
        timeline_rows.append([str(week),band,', '.join(releases) or '—',', '.join(deadlines) or '—',', '.join(milestones) or '—',', '.join(midterms) or '—'])
    final_report=next(m for m in project['milestones'] if 'week' not in m)
    timeline_rows.append(['Final report',final_report['expected_window'],'—','—',final_report['name']+': '+final_report['deadline_rule'],'—'])
    timeline=['# Combined assessment timeline','',
              'Original assignment starts; deadlines extended one week. Each assignment stays open **21 days**. Midterm windows and project deadlines are unchanged.','',
              '**Dates are indicative week bands**, using October 5 as the Week 1 anchor and assuming logical teaching weeks match calendar weeks. Holidays, absences and unscheduled makeups may shift the actual lecture-to-date mapping. `4.2` means the second lecture of teaching Week 4; the weekday is not yet fixed. Each midterm appears in both possible weeks below but is held only once.','',
              table(['Week','Indicative dates','Assignment opens','Assignment due','Project deliverable','Midterm'],timeline_rows),'',
              '- **Overlaps:** A1/A2 during 6.2–7.2; A2/A3 during 8.2–9.2. A4 has no assignment overlap on this plan.',
              '- **Exam preparation:** students may attempt homework before the exam; completion and graded feedback are not required first. Each midterm carries 15% and uses a separate exam slot.',
              '- **Pressure points:** A1 + design report in Week 7; A3 may coincide with the Week 11 midterm option; Week 13 presentations + midterm 3 remain deliberately unresolved.',
              '- **January:** A4 is now at 15.2 (indicatively Jan 11–17), near the expected final-report period. Confirm both against actual lecture dates and the letter-grade deadline. No extra lecture is added.','',
              'Generated by `python3 scripts/phase6_report.py` from accepted decisions. See [assessment details](assessment_schedule.md) and [workload audit](audits/workload.md).','']
    assess=['# Assessment schedule','',intro,'','## Assignments','',assignment_table,'',calendar_note,'',calendar_envelope,'',
            'Keep original releases immediately after the final relevant topic; allow 21 calendar days. A1/A2 and A2/A3 overlap by one week on this relative schedule. Homework may help exam preparation, but submission and graded feedback are not prerequisites for exams.','',
            '## Exams','',exams,'',
            'All exams use separate slots; no final exam. The Week 14 third-exam version including LLM RL is retained only as a future-offering template, not this semester’s schedule. Midterm 3 includes the accepted conceptual CQL question.','',
            '## Cross-assessment pressure','',
            '- A1 is due at 7.2, alongside the Week 7 project design report and potentially the later midterm-1 option. Week 6 exam preparation can use unfinished A1.',
            '- A1/A2 overlap during 6.2–7.2; A2/A3 during 8.2–9.2. The extra week spreads deadlines but does not reduce task scope.',
            '- A3 is due at 11.2, separating it from the Week 10 project progress report. A Week 10 midterm can use unfinished A3; a Week 11 exam may still coincide with its deadline. Exam windows are unchanged.',
            '- A4 is due three weeks after 12.2, at relative 15.2. Verify the January date and spacing from the final project report. It is not a prerequisite for midterm 3.',
            '- The Week 13 midterm/presentation clash is intentionally retained for in-semester resolution.','']
    pp=project['presentation_plan'];slot_used=pp['teams_per_slot']*(pp['talk_minutes']+pp['discussion_minutes'])
    assert slot_used<=pp['slot_minutes']
    proj=['# Project schedule','',intro,'',project_table,'',
          'Teams of 2–3 are encouraged. Individual work or four-person teams are decided case by case.','',
          f'Tentative presentation plan: {pp["slot_count"]} × {pp["slot_minutes"]}-minute slots, {pp["teams_per_slot"]} teams per slot, up to {pp["expected_max_teams"]} teams. '
          f'{slot_used} minutes of talks/discussion leave {pp["slot_minutes"]-slot_used} minutes for transitions in each slot. Attend only the team’s own slot.','',
          pp['finalization_trigger']+' '+pp['schedule_conflict'],'',pp['peer_grading'],'',
          'No project milestone is moved by the new assignment rule. The final report remains one week before letter grades, expected in the third week of January; a date/year is not inferred.','']
    delivery_table=table(['Video','Tentative release','Needed before','Playback minutes','Student effort including playback'],video_rows)
    delivery=['# Initial video and reading plan','',intro,'',delivery_table,'',
              'Release seven calendar days before the relevant live topic. Week-based equivalents are search 9.1 before 10.1 and LLM 12.1 before 13.1. These replace the earlier candidate releases in Weeks 8 and 10.','',
              'Scopes remain semi-frozen with instructor revision during the semester.','',
              table(['Checkpoint week','Action'],[[c['week'],c['action']] for c in videos['checkpoints']]),'',
              'No student readings are assigned this semester. The internal book map is reference material for future planning, not a preparation or examination requirement.','',
              'The LLM preparation now falls in Week 12 alongside offline RL and A4 release; count its full study effort, not just playback. A policy-method supplement is not required by default.','']
    ah=[sum(a['hours'][i] for a in tasks) for i in (0,1)]
    count=policy['aggregation']['counted_count'];subsets=list(combinations(tasks,count))
    three=[min(sum(a['hours'][0] for a in c) for c in subsets),max(sum(a['hours'][1] for a in c) for c in subsets)]
    ph=[sum(m['student_hours'][i] for m in project_est['milestones']) for i in (0,1)]
    vh=[sum(v['student_effort_minutes'][i] for v in video_est)/60 for i in (0,1)]
    contact=len(sessions)*cfg['course']['lecture_minutes']/60;attendance=pp['slot_minutes']/60
    assumptions=review['workload_assumptions'];exam_count=len(grading['midterms'])+1
    prep=[exam_count*x for x in assumptions['exam_preparation_hours_per_midterm']]
    exam=[exam_count*x for x in assumptions['exam_duration_hours_each']]
    routine=[cfg['course']['planned_weeks']*x for x in assumptions['routine_study_hours_per_teaching_week']]
    total=[contact+ah[i]+ph[i]+vh[i]+attendance+prep[i]+exam[i]+routine[i] for i in (0,1)]
    total3=[contact+three[i]+ph[i]+vh[i]+attendance+prep[i]+exam[i]+routine[i] for i in (0,1)]
    def span(v):return number(v[0])+'–'+number(v[1])
    work=['# Phase 6 workload audit','',intro,'',
          '**Assessment:** The instructor judges workload acceptable against a '+span(calendar_constraints['workload_review']['target_total_student_hours'])+'-hour semester target and notes that estimates may be high. Retain the unpiloted sensitivity ranges; extending deadlines does not itself reduce total effort. Calendar mapping and deadline concentrations still need operational confirmation.','',
          table(['Component','Hours per student','Basis'],[
              ['Lecture attendance',number(contact),'26 × 70 minutes, including administration and buffer'],
              ['Assignments, if all four attempted',span(ah),'Accepted tasks; low-confidence active effort estimates'],
              ['Assignments, if exactly three attempted',span(three),'Selection-dependent alternative, not added to all-four workload'],
              ['Project active work',span(ph),'Non-overlapping milestone intervals; includes final report and presentation preparation'],
              ['Presentation attendance',number(attendance),'Own slot only, includes own talk; do not add talk time again'],
              ['Required video study',span(vh),'Includes playback and pauses/review; no separate playback addition'],
              ['Assigned readings','0','Removed from current semester'],
              ['Three midterm sittings',span(exam),'Assumption: '+span(assumptions['exam_duration_hours_each'])+' hours each; actual durations pending'],
              ['Dedicated exam preparation',span(prep),'Assumption: '+span(assumptions['exam_preparation_hours_per_midterm'])+' hours each'],
              ['Routine study',span(routine),'Assumption: '+span(assumptions['routine_study_hours_per_teaching_week'])+' hours per teaching week; excludes other listed work']]),'',
          f'Illustrative total across the teaching period and January completion work: **{span(total)} hours if all four assignments are attempted**, or **{span(total3)} if exactly three are attempted**. '
          'These are sensitivity ranges, not a required-hour promise or an observed course workload. Best-three grading may still induce four submissions. Unattended compute, unusual troubleshooting, travel and unrelated courses are excluded.','',
          assumptions['confidence'],'',
          '## Calendar constraints','',calendar_envelope,'',
          'January unavailability is a delivery constraint: late lessons and any January presentation/exam duties need a feasible arrangement once dates are set. The accepted 26-lecture count is a planning assumption, not proof that the two makeups have been scheduled.','',
          '## Deadline concentration','',
          'A2/A3 average approximately 3.3–4.7 active hours each per week across three weeks. During their one-week overlap, that is roughly 6.7–9.3 assignment hours if work is spread evenly. Adding roughly 4–6 project hours, 2⅓ contact hours and 2–4 routine-study hours gives about 15–22 hours before exam preparation or video study. Actual effort will not be uniform. This is a local pressure scenario, not the course average.','',
          '- Weeks 6–7: A1/A2 overlap; midterm 1 remains in Week 6 or 7. A1 and project design are both due in Week 7.',
          '- Weeks 8–9: A2/A3 overlap while policy concepts are dense; A2 is due at 9.2.',
          '- Week 9: search video arrives during the A2/A3 overlap.',
          '- Weeks 10–11: progress remains due in Week 10; A3 moves to 11.2. Midterm 2 stays in its original Week 10/11 window. An exam in Week 11 can still coincide with A3; no exam rescheduling is inferred.',
          '- Week 12: LLM prerequisite video arrives with offline RL and A4 release; video study is '+span([x/60 for x in next(v for v in video_est if v['id']=='llm_background')['student_effort_minutes']])+' hours on its own.',
          '- Week 13: presentations and midterm 3 overlap by accepted exception; every student attends two presentation hours, not all six.',
          '- January: A4’s relative deadline and the project report need actual dates. If only one week separates them, the workload remains concentrated even with no final exam.','',
          '## Staff and preparation feasibility','',analysis['staffing_audit']['confidence'],'',analysis['staffing_audit']['risk'],'',
          'Accepted tasks require tested scaffolds, automatic checks, fixed run configurations and short common-answer responses. Pilot work was authorized for implementation, not reported as completed. With zero or one TA, this is a material preparation dependency.','',
          '## Live teaching budget','',
          f'{live[0]} teaching minutes + {live[1]} additional administration remain allocated, with {number(live[2])} unallocated usable minutes. '
          'The generic 15% buffer is separate. No assessment slot or video playback was added to lecture minutes. Double DQN/IQL code connections replace parts of existing examples in 6.2/12.2.','',
          '## Calendar and implementation follow-up','',
          '- Map dates, confirm exam durations and review Week 7/9/11/13 and January pressure against the official calendar.',
          '- Workload is accepted in principle. Pilot small scaffolded tasks before release and calibrate estimates against the 150–180-hour target; adjust concrete scope explicitly if needed.',
          '- Preserve the instructor’s deferred operational items as a tracked in-semester checklist. This audit does not claim those tasks are already complete.','']
    weekly=table(['Week','First lecture','Second lecture'],[[w,next(s['title'] for s in sessions if s['week']==w and s['slot']==1),next(s['title'] for s in sessions if s['week']==w and s['slot']==2)] for w in range(1,14)])
    split=grading.get('midterm_weights_percent')
    if split:assert len(split)==exam_count and sum(split)==grading['categories_percent']['midterms']
    grade_text=table(['Component','Course grade'],[[k.title(),str(v)+'%'] for k,v in grading['categories_percent'].items()])+'\n\n'+('Midterms: '+', '.join(str(v)+'%' for v in split)+'.' if split else 'Individual midterm weights remain to be confirmed; equal 15% each is the current recommendation.')
    grade_text+='\n\nAssignments are individual. '+policy['aggregation']['formula']+'. '+policy['aggregation']['completion_rule']+' No final exam. Midterms use separate slots.\n\n'+exams
    policies=policy['llm_use']['disclosure']+' '+policy['llm_use']['no_credit_rule']+'\n\n'+'\n'.join('- '+x for x in policy['llm_use']['report_requirements'])+'\n\nConcrete rubric, penalty scope and the example report will be finalized during the semester, as directed. No prompt-count threshold or new penalty is inferred in this draft.'
    pending='Official dated calendar, exact exam dates/durations'+('' if split else ', individual midterm weights')+', and January deadline mapping remain to be finalized. Presentation slots and the Week 13 clash will be resolved during the semester after proposals/team freeze. Readings are removed. Concrete assignment rubrics/examples are intentionally deferred.'
    vals={'course_name':cfg['course']['name'],'state':'Syllabus content and workload accepted in principle. Weekly teaching sequence is unchanged. Revised assignment windows are incorporated; exact calendar dates remain provisional.',
          'overview':'Develop a coherent foundation in tabular and approximate RL, connect it to deep/model-based/offline methods, and use those foundations to understand RL-based LLM post-training. Expected background: '+', '.join(cfg['audience']['assumed_background'])+'. Required work is designed around personal-laptop access; no mandatory LLM-training assignment.',
          'outcomes':'\n'.join('- '+o['id']+': '+o['text'] for o in cfg['learning_outcomes']),
          'weekly_plan':weekly+'\n\nSee the [detailed lecture plan](lecture_plan.md) for accepted bounded scopes and time estimates.',
          'grading':grade_text,'assignment_schedule':assignment_table+'\n\n'+calendar_note+'\n\n'+calendar_envelope+'\n\nSee [accepted assignment design](assignments.md) for task scope.',
          'project':project_table+'\n\nTeams of 2–3 encouraged; individual/four-person exceptions case by case. Three tentative two-hour presentation slots, eight teams per slot; attend only your own slot. Presentation scheduling/peer grading will be settled during the semester. See [project schedule](project_schedule.md).',
          'delivery':delivery_table+'\n\nVideos are required background, tentatively released seven days before use; scopes reviewed in Weeks 4, 8 and 11. No assigned readings this semester.',
          'policies':policies,'pending':pending}
    syllabus=(ROOT/'course/syllabus/template.md').read_text()
    for key,value in vals.items():syllabus=syllabus.replace('{{'+key+'}}',value)
    assert '{{' not in syllabus,'Unresolved template placeholder'
    consistency=['# Phase 6 course-design consistency audit','',intro,'',
                 '**Phase 5: complete. Phase 6: syllabus content and workload accepted in principle; revised timeline ready for review. Final dated design remains provisional.**','',
                 table(['Check','Result','Evidence / limitation'],[
                     ['Weekly sequence and timing','Unchanged','Machine comparison of session IDs, weeks, slots, titles, teaching and administration against the start-of-Phase-6 baseline.'],
                     ['Topic/mastery revisions','Accepted','Double DQN target patch and IQL losses are Core implementation; maximization bias clarified Core. No topic-time addition.'],
                     ['Learning outcomes','Supported','All eight mapped to live sessions in curriculum consistency audit; Core assessment paths in assignment alignment audit.'],
                     ['Assignments','Pass revised relative schedule','21 elapsed days after original releases; one-week A1/A2 and A2/A3 overlaps. Exact dates need calendar.'],
                     ['Best-three mastery evidence','Accepted limitation','Omitting an assignment can leave implementation evidence incomplete for its topic. No hidden all-four hurdle.'],
                     ['Project','Accepted exception','Milestones/weights unchanged; presentation/midterm 3 clash intentionally deferred.'],
                     ['Videos','Tentative plan','Seven-day lead; Weeks 9 and 12 on uninterrupted schedule, with in-semester checkpoints.'],
                     ['Readings','Removed','No required/optional reading assignment or reading-only examination requirement.'],
                     ['Grading totals','Pass','45 + 35 + 20 = 100; project components total 35; assignment best-three normalizes to 20.'],
                     ['Exam weights','Confirmed' if split else 'Open','Equal split accepted.' if split else '45% category accepted; equal 15% recommendation not silently adopted.'],
                     ['Total workload','Accepted in principle','Instructor target 150–180 hours; sensitivity estimates retained pending task pilots. Dates/durations remain provisional.'],
                     ['Operational rubric/examples','Deferred by instructor','Outside Phase 5 exit gate; tracked for in-semester preparation before task release.'],
                     ['Syllabus','Consistent draft','Generated from accepted facts; unresolved dates/policies explicitly marked.']]),'',
                 'See the [compact combined timeline](../assessment_timeline.md). No change to the weekly teaching plan was needed. Original assignment releases are retained and deadlines extended seven days. Exam windows and project milestones remain unchanged.','',
                 'See [workload](workload.md), [assessment schedule](../assessment_schedule.md), [project schedule](../project_schedule.md), [video plan](../video_plan.md), and [syllabus draft](../syllabus.md). No Phase 7 artifact construction or final design freeze is claimed.','']
    complete=['# Phase 5 completion','',intro,'',
              '**High-level assessment/project/reading design complete by instructor acceptance.**','',
              '- Four individual assignments, best-three aggregation, tasks, starter approach and bounded Double DQN/IQL implementation scope accepted.',
              '- Project scope, milestone weights/lengths/deadline rules and team policy accepted; presentation scheduling conflict explicitly deferred.',
              '- Readings removed from this semester; two prerequisite videos retained.',
              '- Effort estimates, assessment alignment and grading-capacity risks documented. Pilots are future work, not claimed completed.',
              '- Rubric/penalty detail and example LLM-use report explicitly deferred to the semester, outside the Phase 5 gate.',
              '- Phase 6 authorized: apply the newer assignment/video release rules and audit combined workload/calendar fit.', '',
              'Remaining Phase 6 issues are calendar mapping and exam details; syllabus content and workload have instructor approval in principle. Weekly lecture sequence remains unchanged.','']
    return {'output/assessment_timeline.md':'\n'.join(timeline),'output/assessment_schedule.md':'\n'.join(assess),'output/project_schedule.md':'\n'.join(proj),
            'output/video_plan.md':'\n'.join(delivery),'output/syllabus.md':syllabus,
            'output/audits/workload.md':'\n'.join(work),'output/audits/design_consistency.md':'\n'.join(consistency),
            'analysis/phase5_completion.md':'\n'.join(complete)}


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for name,content in build().items():
        path=ROOT/name
        if args.check:assert path.exists() and path.read_text()==content,f'Stale generated file: {name}'
        else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
    print('Phase 6 package valid: weekly baseline and assignment releases unchanged; 21-day windows, prerequisites, grading and video lead checked. Calendar remains provisional.')


if __name__=='__main__':main()
