#!/usr/bin/env python3
"""Generate the Phase 4 consistency review and curriculum views, without accepting proposals.

Usage: python3 scripts/phase4_audit.py [--check]
Offline; requires PyYAML and the existing Phase 3 auditor.
"""
import argparse
import re
import yaml
from phase3_audit import ROOT, read, number, table, build as phase3_build


def build():
    _, totals = phase3_build()  # Validate topics, taxonomy, time, segments and prerequisite order.
    cfg = read('config/course.yaml')
    p = read('analysis/phase3_proposal.yaml')
    d = read(p['accepted_topics_source'])
    review = read('analysis/phase4_review.yaml')
    topics = {t['id']: t for t in read(p['evidence_source'])['topics']}
    accepted = {g['id']: g for g in d['scope_decisions']}
    groups = {g['id']: {**accepted[g['accepted_scope_ref']], **g} for g in p['groups']}
    sessions = {s['id']: s for s in d['lecture_plan']}
    labels = {k: f'{s["week"]}.{s["slot"]}' for k, s in sessions.items()}
    video_data = yaml.safe_load(re.findall(r'```yaml\n(.*?)\n```', (ROOT/p['accepted_videos_source']).read_text(), re.S)[0])
    videos = {v['id']: v for v in video_data['videos']}
    for v in p['videos']:
        v.update(videos[v['id']])
        v['release_week']=sessions[v['before']]['week']-video_data['release_policy']['lead_days']//7
    outcomes = {o['id']: o for o in cfg['learning_outcomes']}
    assert {o['id'] for o in review['outcomes']} == outcomes.keys(), 'Outcome coverage incomplete'
    assert len(review['outcomes']) == len(outcomes), 'Duplicate outcome mapping'
    for o in review['outcomes']:
        assert o['sessions'] and set(o['sessions']) <= sessions.keys() and o['assessment']
    assert d['phase4_authorization']['freeze_state'] == 'frozen'
    assert all(not {'role', 'status', 'status_scope'} & g.keys() for g in p['groups']), 'Accepted metadata duplicated in analysis'
    assert p['handoff']['phase3_state'] == 'complete'
    for e in review['status_evidence']:
        assert set(e['groups']) <= groups.keys() and e['url'].startswith('https://')
    required = {gid: g for gid, g in groups.items() if g['role'] != 'extension'}
    core = {gid: g for gid, g in groups.items() if g['role'] == 'core'}
    for gid, g in core.items():
        taught = [s for s in sessions.values() if gid in s['group_ids']]
        assert taught and any(s['worked_activity'] for s in taught), f'No worked core activity: {gid}'
        assert g['scope'] and g['mastery'] and g['assessment_expectation']
    pending_roles = [gid for gid in required if 'role' not in accepted[gid]]
    pending_status = [gid for gid in required if 'status' not in accepted[gid]]
    assert not pending_roles and not pending_status, 'Freeze requires accepted metadata'
    teaching, admin, spare, topic_count = totals
    duration = cfg['course']['lecture_minutes']
    fraction = cfg['design']['planned_content_fraction']
    overheads = cfg['design']['in_class_overheads']
    overhead = sum(x['minutes'] for x in overheads)
    contact = len(sessions)*duration
    capacity = contact*fraction-overhead
    video_play = [sum(v['playback_minutes'][i] for v in p['videos']) for i in (0, 1)]
    video_effort = [sum(v['student_effort_minutes'][i] for v in p['videos']) for i in (0, 1)]
    policy_sessions = [sessions[k] for k in p['policy_audit']['session_ids']]
    policy_teaching = sum(s['teaching_minutes'] for s in policy_sessions)
    policy_admin = sum(s['administration_minutes'] for s in policy_sessions)
    policy_capacity = len(policy_sessions)*duration*fraction-policy_admin
    policy_buffer = len(policy_sessions)*duration*(1-fraction)
    policy_overrun = max(0, policy_teaching*(1+p['policy_audit']['pace_stress_fraction'])-policy_capacity)
    offline_sessions = [s for s in sessions.values() if s['week']==sessions['offline_failure']['week']]
    offline_spare = sum(duration*fraction-s['teaching_minutes']-s['administration_minutes'] for s in offline_sessions)
    offline_first_spare = duration*fraction-sessions['offline_failure']['teaching_minutes']-sessions['offline_failure']['administration_minutes']
    def scheduled(gid):
        return ', '.join(labels[k] for k, s in sessions.items() if gid in s['group_ids']) or 'Preparation video / optional only'
    def role(gid):
        return groups[gid]['role'].title() + (' (accepted)' if 'role' in accepted[gid] else ' (proposed)')
    def group_name(gid):
        g = groups[gid]
        return g.get('display_name') or ', '.join(topics[t]['name'] for t in g['topic_ids'][:2]) + (' and related concepts' if len(g['topic_ids'])>2 else '')
    common = ('Generated by `python3 scripts/phase4_audit.py`; edit authoritative decisions or the working analysis, then regenerate. '
              '**Curriculum frozen by instructor decision.** Scope, mastery, role, status, delivery and baseline lecture sequence are accepted. Assessment paths remain proposals; detailed timings remain planning estimates. '
              'CQL’s Exposure role is explicitly accepted.')
    audit = ['# Curriculum consistency audit', '', common, '',
             '## Recommendation', '', review['recommendation'], '',
             '**Phase 3 handoff: passed. Phase 4 technical review: passed with the pacing and workload qualifications below. '
             'Formal freeze: accepted.** No unresolved high-impact addition/removal remains.', '',
             f'{len(required)} required topic groups and {len(core)} accepted Core groups reviewed; {topic_count} normalized topic dispositions including optional extensions. '
             f'{len(pending_roles)} required groups still have proposed roles; {len(pending_status)} have proposed status metadata. '
             'All group masteries and required video scopes are accepted. These counts describe metadata acceptance, not missing teaching content.', '',
             '## Time and workload', '',
             table(['Quantity','Minutes / treatment'], [
                 ['Scheduled contact', number(contact)], ['Generic buffer (separate)', number(contact*(1-fraction))],
                 ['Configured syllabus administration', number(overhead)], ['Usable budget after fraction and syllabus', number(capacity)],
                 ['Teaching blocks', teaching], ['Additional checkpoint/synthesis administration', admin],
                 ['Unallocated within usable budget', number(spare)],
                 ['Required video playback', f'{video_play[0]}–{video_play[1]}'],
                 ['Required video student effort (includes playback)', f'{video_effort[0]}–{video_effort[1]}'],
                 ['Project presentations', 'Outside class: zero lecture minutes; preparation/attendance workload to be designed']]), '',
             f'All {len(sessions)} sessions fit their local planning allowance; topic IDs within a teaching block are not charged separately. '
             f'The {number(spare)}-minute semester margin is spread across sessions and is not freely transferable to any week. '
             'The generic buffer may be used in delivery, at the expense of questions/examples/consolidation. '
             'Teaching and video effort estimates are not a completed total student-workload budget.', '',
             f'The {len(policy_sessions)} policy lectures allocate {policy_teaching} teaching minutes and {policy_admin} administration minutes, leaving {number(policy_capacity-policy_teaching)} within their planning allowance. '
             f'A {number(p["policy_audit"]["pace_stress_fraction"]*100)}% teaching overrun needs {number(policy_overrun)} minutes of their {number(policy_buffer)}-minute generic buffer in aggregate; individual lectures may need redistribution. '
             f'SAC remains {d["constraints"]["sac_live_minutes"]} minutes, without a proof or coding workshop. '
             f'The offline week has {number(offline_spare)} unallocated minutes, only {number(offline_first_spare)} in its first session: optional five-minute LSTD and IRL mentions compete for that local margin. '
             'CQL already occupies five minutes in 12.2; the clarification adds zero time.', '',
             'See the [full time audit](../../analysis/time_budget.md), [policy sensitivity audit](../../analysis/policy_time_budget.md), '
             'and [weekly lecture plan](../lecture_plan.md).', '',
             '## Findings', '', table(['ID','Check','Result','Judgment'],[[f['id'],f['topic'],f['result'],f['detail']] for f in review['findings']]), '',
             '## Learning outcomes and planned evidence', '',
             'Coverage and assessment paths are audit judgments. High-level assessment scope is accepted in decisions; concrete rubrics remain deferred. See the Phase 6 workload and design audits.', '',
             table(['Outcome','Live support (week.slot)','Proposed assessment evidence'],[[o['id']+': '+outcomes[o['id']]['text'], ', '.join(labels[s] for s in o['sessions']), o['assessment']] for o in review['outcomes']]), '',
             '## Core depth review', '',
             'Session windows are shared with other groups. They are not per-topic time allocations. '
             'Adequacy is conditional on the bounded accepted scope and representative examples; arithmetic alone does not establish learning.', '',
             table(['Accepted Core group','Accepted bounded scope','Accepted mastery','Sessions','Proposed assessment path'],[[group_name(gid),g['scope'],', '.join(g['mastery']),scheduled(gid),', '.join(g['assessment_expectation'])] for gid,g in core.items()]), '',
             '## Status evidence and limits', '',
             'These selective primary-source checks support scoped classification inferences. They are not required readings, a refreshed source inventory, or evidence of industry prevalence. '
             'Foundational/book and source-course observations remain in [normalized evidence](../../analysis/normalized_topics.yaml).', '']
    for e in review['status_evidence']:
        audit += [f'- **{e["id"]}** — {e["observation"]} {e["inference"]} [{e["title"]}]({e["url"]}). '
                  f'{e["period"]}; {e["locator"]}; retrieved {e["retrieved"]}.']
    audit += ['', '## Remaining decision and next phase boundary', '',
              'The instructor adopted the roles/status and baseline sequence shown in [topic details](../topic_details.md), preserving the accepted scope/mastery and video checkpoints. '
              'Acceptance is logged and authoritative classifications and sessions now reside in decisions. Optional topics remain optional. '
              'Detailed lecture minutes remain estimates that may be adjusted without expanding the accepted scope.', '',
              'Phase 5 high-level design is accepted; Phase 6 integrates syllabus, schedule and workload. '
              'Concrete rubrics and example-report work are deferred to the semester. Deferred LSTD/IRL choices and the future-topic register remain outside the base allocation. Exam scheduling must preserve the frozen teaching budget or trigger an explicit revision.', '',
              '**Confidence:** '+review['confidence'], '']
    details = ['# Topic scope and mastery', '', common, '',
               'Sources: [accepted topic decisions](../decisions/topic_decisions.yaml), [assessment/video-detail proposals](../analysis/phase3_proposal.yaml), '
               '[video decisions](../decisions/video_decisions.md). See the [consistency audit](audits/curriculum_consistency.md) for the freeze record.', '',
               '**Mastery is group-level and bounded by the stated scope.** Derive/implement applies to representative methods, not automatically every ID in the group. '
               'Research/practice status is also scoped: mixed groups can contain foundational concepts and a contemporary algorithm. '
               'Optional extensions have no compulsory assessment or preparation.', '',
               '## Topic index', '',
               table(['Topic','Role','Accepted group mastery','Placement'],[[f'[{topics[t]["name"]}](#{t})',role(gid),', '.join(g['mastery']),scheduled(gid)] for gid,g in groups.items() for t in g['topic_ids']]), '',
               '## Bounded teaching scopes', '']
    for gid,g in groups.items():
        details += [*(f'<a id="{t}"></a>' for t in g['topic_ids']), '', '### '+group_name(gid), '',
                    f'Group `{gid}`. **{role(gid)}; accepted mastery: {", ".join(g["mastery"])}.**', '',
                    '**Topics:** '+ '; '.join(f'{topics[t]["name"]} (`{t}`)' for t in g['topic_ids'])+'.', '',
                    g['scope'], '', f'**Delivery:** {", ".join(g["delivery"])}. **Sessions:** {scheduled(gid)}. '
                    f'**Proposed assessment path:** {", ".join(g["assessment_expectation"])}.', '',
                    '**Accepted status:** '+(', '.join(g['status']) or 'Not classified for optional extensions; review if included')+'. '+g.get('status_scope',''), '']
    plan = ['# Weekly lecture plan', '', common, '',
            'Minutes are planning estimates, not commitments or student workload. Ranges represent uncertain teaching demand. '
            'Administration is separate. Configured syllabus time is additional to the 85% allowance; generic buffer is not allocated twice. '
            'Scope changes require an explicit decision; pacing can evolve within the accepted scope.', '',
            '## Semester at a glance', '',
            table(['Week.slot','Lecture','Teaching','Other admin','Demand range','Unallocated'],[[labels[k],s['title'],s['teaching_minutes'],s['administration_minutes'],f'{s["teaching_range"][0]}–{s["teaching_range"][1]}',number(duration*fraction-(sum(h['minutes'] for h in overheads if h['week']==s['week']) if s['slot']==1 else 0)-s['teaching_minutes']-s['administration_minutes'])] for k,s in sessions.items()]), '',
            f'Teaching {teaching} + additional administration {admin} = {teaching+admin} of {number(capacity)} usable minutes; '
            f'{number(spare)} unallocated. Configured syllabus briefing: {overhead} minutes in 1.1. Project presentations remain outside class.', '',
            '## Session detail', '']
    for sid,s in sessions.items():
        plan += [f'### {labels[sid]} — {s["title"]}', '',
                 '**Topic groups:** '+ '; '.join(group_name(gid) for gid in s['group_ids'])+'.', '',
                 '**Prerequisite sessions:** '+(', '.join(labels[x] for x in s['requires']) or 'Configured entry background')+'.', '',
                 '**Worked activity:** '+s['worked_activity'], '', '**Pacing:** '+s['feasibility_note']+f' Confidence: {s["confidence"]}.', '']
        if s.get('segments'):
            segments = [[v['label'],d['constraints'][v['accepted_minutes_ref']] if 'accepted_minutes_ref' in v else v['minutes']] for v in s['segments']]
            plan += [table(['Exclusive teaching segment','Minutes'],segments), '']
    plan += ['## Required preparation videos', '',
             'Scopes are semi-frozen with Weeks 4, 8 and 11 review checkpoints. Release weeks and durations below are estimates. '
             'Study effort includes playback; do not add both columns when budgeting student workload. Supplementary policy video remains a contingency.', '']
    for v in p['videos']:
        a=videos[v['id']]
        plan += [f'### {v["id"].replace("_", " ").title().replace("Llm", "LLM")}', '',
                 f'Proposed release: Week {v["release_week"]}; required before {labels[v["before"]]}. '
                 f'Playback {v["playback_minutes"][0]}–{v["playback_minutes"][1]} minutes; student effort {v["student_effort_minutes"][0]}–{v["student_effort_minutes"][1]} minutes. Confidence: {v["confidence"]}.', '',
                 '**Accepted scope:** '+str(a['scope']).rstrip('.')+'.', '',
                 '**Proposed outline detail:** '+ '; '.join(v['additional_scope_proposal'])+'.', '', v['fallback'], '']
    plan += ['## Delivery contingencies', '', p['audit_notes']['pressure_response'], '',
             'LSTD and IRL are optional five-minute substitutions, not scheduled additions. '
             'Required questions deferred beyond class need an accessible recap, with its time counted. '
             'Project checkpoint administration is included; assignment/project effort and outside-class presentation time remain Phase 5 work.', '']
    completion = ['# Phase 3 completion and Phase 4 handoff', '',
                  'Generated by `python3 scripts/phase4_audit.py` from accepted decisions and the audited proposal.', '',
                  '**Phase 3 complete.** The instructor reviewed R1–R6, pacing, video use and masteries, clarified Conservative Q-Learning, and authorized Phase 4.', '',
                  '- Major scope additions/removals resolved; no remaining high-impact Phase 3 choice.',
                  '- CQL remains the existing five-minute Exposure/explain contrast in Week 12.2; no added time.',
                  '- Accepted scope, mastery, delivery and fixed durations are in decisions. Roles/status and the baseline lecture sequence have since been accepted at freeze. Assessment paths remain proposals.',
                  f'- Live budget passes: {teaching} teaching + {admin} additional administration of {number(capacity)} usable minutes; {number(spare)} unallocated. Generic buffer is separate.',
                  '- Prerequisite order and two required video scopes are sufficiently resolved, with Weeks 4, 8 and 11 delivery checkpoints.',
                  '- Optional LSTD/IRL and the future-topic register do not impose current requirements.', '',
                  'Evidence limitations: teaching durations are estimates, source coverage is not a vote or a measured pacing model, and total assessment/project/presentation workload is not yet designed. '
                  'Policy-method and modern-unit pacing need observation during teaching. No collection/normalization rerun was needed.', '',
                  'Next action: review the [Phase 4 consistency audit](../output/audits/curriculum_consistency.md), [topic details](../output/topic_details.md), '
                  'and [weekly lecture plan](../output/lecture_plan.md). Curriculum freeze is now accepted; Phase 5 high-level design is complete; the instructor has frozen the final syllabus and closed Phase 6. Current artifact-work phase is recorded in `decisions/syllabus_decisions.yaml`.', '']
    return {'output/audits/curriculum_consistency.md':'\n'.join(audit), 'output/topic_details.md':'\n'.join(details),
            'output/lecture_plan.md':'\n'.join(plan), 'analysis/phase3_completion.md':'\n'.join(completion)}


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true',help='Validate and check generated files without writing')
    args=parser.parse_args()
    for name, content in build().items():
        path=ROOT/name
        if args.check:
            assert path.exists() and path.read_text()==content, f'Stale generated file: {name}'
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_text(content)
    print('Phase 4 consistency review valid; four generated views current. Curriculum and final syllabus frozen; Phase 6 closed.')


if __name__=='__main__':
    main()
