#!/usr/bin/env python3
"""Refresh a derived Markdown view of a manually edited PPTX. Standard library only.

Default: python3 scripts/pptx_to_markdown.py
Other deck: python3 scripts/pptx_to_markdown.py course/lectures/week02/bellman_chatgpt.pptx
Check freshness without writing: add --check

Reads saved slide order, editable text, tables, links, images and speaker notes. Does not
open PowerPoint, modify PPTX files, accept decisions, OCR images or rebuild slides.
"""
import argparse
import hashlib
import io
import os
from pathlib import Path, PurePosixPath
import posixpath
import re
import tempfile
from urllib.parse import quote, unquote
from xml.etree import ElementTree as ET
from zipfile import BadZipFile, ZipFile

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / 'course/lectures/week01/nuts_and_bolts_chatgpt.pptx'
MARKER = '<!-- Generated by scripts/pptx_to_markdown.py; do not edit. -->'
NS = {
    'p': 'http://schemas.openxmlformats.org/presentationml/2006/main',
    'a': 'http://schemas.openxmlformats.org/drawingml/2006/main',
    'r': 'http://schemas.openxmlformats.org/officeDocument/2006/relationships',
}


def tag(prefix, name):
    return f'{{{NS[prefix]}}}{name}'


def escape(text):
    return re.sub(r'([\\`*_\[\]<>|])', r'\\\1', text)


def relationships(archive, owner):
    part = PurePosixPath(owner)
    rel_path = str(part.parent / '_rels' / (part.name + '.rels'))
    if rel_path not in archive.namelist():
        return {}
    result = {}
    for rel in ET.fromstring(archive.read(rel_path)):
        external = rel.get('TargetMode') == 'External'
        target = rel.get('Target', '')
        if not external:
            target = posixpath.normpath(posixpath.join(str(part.parent), unquote(target))).lstrip('/')
            if target.startswith('../'):
                raise ValueError(f'Relationship escapes package: {target}')
        result[rel.get('Id')] = (target, external, rel.get('Type', ''))
    return result


def paragraphs(parent, rels):
    """Paragraphs as plain text and Markdown, including native bullets and links."""
    result = []
    for paragraph in parent.findall('a:p', NS):
        plain, rich = [], []
        for child in paragraph:
            if child.tag == tag('a', 'br'):
                plain.append('\n')
                rich.append('  \n')
            elif child.tag in (tag('a', 'r'), tag('a', 'fld')):
                # a:r/a:fld carry text in a:t, not in formatting properties.
                text = ''.join(t.text or '' for t in child.findall('a:t', NS))
                plain.append(text)
                value = escape(text)
                link = child.find('a:rPr/a:hlinkClick', NS)
                if link is not None:
                    relation = rels.get(link.get(tag('r', 'id')))
                    if relation and relation[1] and re.match(r'^(https?://|mailto:)', relation[0], re.I):
                        uri = quote(relation[0], safe=':/?#@!$&\'()*+,;=%')
                        value = f'[{value}](<{uri}>)'
                rich.append(value)
        text, formatted = ''.join(plain).strip(), ''.join(rich).strip()
        if not text:
            continue
        props = paragraph.find('a:pPr', NS)
        prefix = ''
        if props is not None and props.find('a:buNone', NS) is None:
            level = max(0, min(8, int(props.get('lvl', '0'))))
            if props.find('a:buChar', NS) is not None:
                prefix = '  ' * level + '- '
            elif props.find('a:buAutoNum', NS) is not None:
                start = props.find('a:buAutoNum', NS).get('startAt', '1')
                prefix = '  ' * level + f'{start}. '
        result.append((text, prefix + formatted))
    return result


def shape_nodes(tree):
    for child in tree:
        if child.tag == tag('p', 'grpSp'):
            yield from shape_nodes(child)
        elif child.tag in {tag('p', 'sp'), tag('p', 'pic'), tag('p', 'graphicFrame')}:
            yield child


def extract_slides(data, image_handler=None):
    """Use the presentation relationship order, never slide filename sorting."""
    slides = []
    with ZipFile(io.BytesIO(data)) as archive:
        presentation = ET.fromstring(archive.read('ppt/presentation.xml'))
        rels = relationships(archive, 'ppt/presentation.xml')
        for slide_id in presentation.findall('p:sldIdLst/p:sldId', NS):
            slide_path, external, kind = rels[slide_id.get(tag('r', 'id'))]
            if external or not kind.endswith('/slide'):
                raise ValueError('Invalid slide relationship')
            slide = ET.fromstring(archive.read(slide_path))
            slide_rels = relationships(archive, slide_path)
            blocks, title = [], None
            tree = slide.find('p:cSld/p:spTree', NS)
            if tree is None:
                raise ValueError(f'Missing shape tree: {slide_path}')
            for shape in shape_nodes(tree):
                if shape.tag == tag('p', 'sp'):
                    ph = shape.find('p:nvSpPr/p:nvPr/p:ph', NS)
                    ph_type = ph.get('type') if ph is not None else None
                    if ph_type in {'dt', 'ftr', 'hdr', 'sldNum'}:
                        continue
                    body = shape.find('p:txBody', NS)
                    if body is None:
                        continue
                    ps = paragraphs(body, slide_rels)
                    if ps and ph_type in {'title', 'ctrTitle'} and title is None:
                        title = ps[0][0].splitlines()[0]
                    if ps:
                        blocks.append('\n\n'.join(rich for _, rich in ps))
                elif shape.tag == tag('p', 'pic'):
                    props = shape.find('p:nvPicPr/p:cNvPr', NS)
                    label = (props.get('descr') or props.get('title') or props.get('name')) if props is not None else 'Image'
                    blip = shape.find('p:blipFill/a:blip', NS)
                    relation = slide_rels.get(blip.get(tag('r', 'embed'))) if blip is not None else None
                    if image_handler and relation and not relation[1]:
                        target = relation[0]
                        blocks.append(image_handler(label or 'Image', target, archive.read(target)))
                    else:
                        blocks.append(f'*Image: {escape(label or "Image")} (image content is not transcribed).*')
                else:
                    table = shape.find('.//a:tbl', NS)
                    if table is None:
                        blocks.append('*Chart, diagram or embedded object: inspect the PPTX.*')
                        continue
                    rows = []
                    merged = False
                    for row in table.findall('a:tr', NS):
                        cells = []
                        for cell in row.findall('a:tc', NS):
                            merged |= any(int(cell.get(key, '1')) > 1 for key in ('gridSpan', 'rowSpan'))
                            merged |= any(cell.get(key) in {'1', 'true'} for key in ('hMerge', 'vMerge'))
                            body = cell.find('a:txBody', NS)
                            ps = paragraphs(body, slide_rels) if body is not None else []
                            cells.append('<br>'.join(rich.replace('\n', '<br>') for _, rich in ps))
                        rows.append(cells)
                    if rows:
                        width = max(map(len, rows))
                        rows = [row + [''] * (width - len(row)) for row in rows]
                        lines = ['| ' + ' | '.join(rows[0]) + ' |', '| ' + ' | '.join(['---'] * width) + ' |']
                        lines += ['| ' + ' | '.join(row) + ' |' for row in rows[1:]]
                        if merged:
                            lines.append('\n*Merged cells are flattened. Inspect the PPTX for their layout.*')
                        blocks.append('\n'.join(lines))
            notes = []
            for note_path, external, kind in slide_rels.values():
                if external or not kind.endswith('/notesSlide'):
                    continue
                note = ET.fromstring(archive.read(note_path))
                note_rels = relationships(archive, note_path)
                for shape in note.findall('.//p:sp', NS):
                    ph = shape.find('p:nvSpPr/p:nvPr/p:ph', NS)
                    if ph is not None and ph.get('type') in {'sldImg', 'sldNum', 'dt', 'ftr', 'hdr'}:
                        continue
                    body = shape.find('p:txBody', NS)
                    if body is not None:
                        notes.extend(rich for _, rich in paragraphs(body, note_rels))
            slides.append({'title': title or 'Untitled slide', 'hidden': slide.get('show') == '0',
                           'blocks': blocks, 'notes': notes})
    return slides


def render(source, output, assets=None):
    """Render without writes; optionally collect linked image paths and bytes."""
    data = source.read_bytes()
    def image_link(label, member, blob):
        extension = PurePosixPath(member).suffix.lower()
        if extension not in {'.png', '.jpg', '.jpeg', '.gif', '.svg', '.bmp', '.tif', '.tiff', '.emf', '.wmf'}:
            return f'*Image: {escape(label)} (unsupported format; inspect the PPTX).*'
        name = hashlib.sha256(blob).hexdigest() + extension
        asset = output.parent / (output.stem + '_assets') / name
        if assets is not None:
            assets[asset] = blob
        relative = quote(os.path.relpath(asset, output.parent).replace(os.sep, '/'), safe='/')
        return f'![{escape(label)}](<{relative}>)'
    slides = extract_slides(data, image_link)
    relative = quote(os.path.relpath(source, output.parent).replace(os.sep, '/'), safe='/')
    lines = [MARKER, f'<!-- Source SHA-256: {hashlib.sha256(data).hexdigest()} -->', '',
             f'# {source.stem.replace("_", " ").capitalize()}', '',
             f'Source: [editable PowerPoint](<{relative}>). Edit the PPTX, save it, then refresh this view.', '',
             'This is a text view, not a curriculum acceptance record or a slide-generation input. '
             'It includes saved slide order, editable text, tables, links, embedded images and speaker notes. '
             'Images are copied without modification to the adjacent assets directory. '
             'Object order may differ from visual reading order. Formatting, image crops, charts, equations, animation and layout '
             'must be reviewed in the PPTX; images are not OCR-transcribed. '
             'A separate experimental reconstruction can use this view, but cannot restore the original layout.', '']
    for n, slide in enumerate(slides, 1):
        hidden = ' (hidden)' if slide['hidden'] else ''
        lines += [f'## Slide {n} — {escape(slide["title"])}{hidden}', '', '**On slide**', '',
                  '\n\n'.join(slide['blocks']) or '*No extractable slide text.*', '', '**Speaker notes**', '',
                  '\n\n'.join(slide['notes']) or '*No speaker notes.*', '']
    return '\n'.join(lines), len(slides)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', nargs='?', type=Path, default=DEFAULT_SOURCE)
    parser.add_argument('-o', '--output', type=Path)
    parser.add_argument('--check', action='store_true', help='check freshness without writing')
    args = parser.parse_args()
    source = args.source.resolve()
    if source.suffix.lower() != '.pptx':
        parser.error('Source must be a PPTX file.')
    if args.output:
        output = args.output.resolve()
    else:
        try:
            output = (ROOT / 'output' / source.relative_to(ROOT / 'course')).with_suffix('.md').resolve()
        except ValueError:
            parser.error('Use --output for a source outside course/.')
    if not output.is_relative_to((ROOT / 'output').resolve()) or output.suffix != '.md':
        parser.error('Markdown output must be under output/ and end in .md.')
    try:
        assets = {}
        content, count = render(source, output, assets)
        previous = output.read_text() if output.exists() else None
        if args.check:
            if previous != content or any(not p.is_file() or p.read_bytes() != blob for p, blob in assets.items()):
                parser.exit(1, f'Stale or missing view: {output}\nRun without --check after saving the PPTX.\n')
            print(f'Current: {count} slides; PPTX unchanged.')
            return
        if previous is not None and not previous.startswith(MARKER):
            parser.error('Refusing to replace a file not created by this exporter.')
        # Never follow an assets-directory symlink out of generated output.
        for asset, blob in assets.items():
            if not asset.resolve().is_relative_to((ROOT / 'output').resolve()):
                raise ValueError('Image output escapes output/.')
            if asset.exists() and asset.read_bytes() != blob:
                raise ValueError(f'Refusing to replace modified image: {asset}')
        for asset, blob in assets.items():
            asset.parent.mkdir(parents=True, exist_ok=True)
            if not asset.exists():
                with asset.open('xb') as f:
                    f.write(blob)
        output.parent.mkdir(parents=True, exist_ok=True)
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', dir=output.parent, delete=False) as f:
                temporary = Path(f.name)
                f.write(content)
            temporary.replace(output)
        finally:
            if temporary is not None:
                temporary.unlink(missing_ok=True)
        print(f'Updated {output.relative_to(ROOT)}: {count} slides. PPTX unchanged.')
    except (OSError, ValueError, KeyError, ET.ParseError, BadZipFile) as exc:
        parser.exit(1, f'Cannot extract PPTX: {exc}\n')


if __name__ == '__main__':
    main()
