#!/usr/bin/env python3
"""Render the accepted week-level schedule only; do not run audits or edit syllabi."""
from datetime import date, timedelta
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]


def decision(kind):
    text = (ROOT / f'decisions/{kind}_decisions.md').read_text()
    return yaml.safe_load(text.split('```yaml\n', 1)[1].split('```', 1)[0])


def build():
    schedule = yaml.safe_load((ROOT / 'decisions/schedule_decisions.yaml').read_text())
    assignments = decision('assignment')['assignments']
    project = decision('project')
    grading = decision('grading')
    anchor = date(2026, 10, 5)
    rows = []
    for week in range(4, 17):
        opens = [a['id'] for a in assignments if a['schedule']['release_week'] == week]
        due = [a['id'] + (' (' + a['schedule']['due_placement'] + ')' if a['schedule']['due_placement'] != 'unspecified' else '')
               for a in assignments if a['schedule']['due_week'] == week]
        milestones = [m['name'] + (' (' + m['placement'] + ')' if 'placement' in m else '')
                      for m in project['milestones'] if m.get('week', m.get('target_week')) == week]
        exams = [m['id'].replace('midterm_', 'MT') for m in grading['midterms'] if week in m['window_weeks']]
        if grading['third_midterm']['current_semester_alternative']['week'] == week:
            exams.append('MT3')
        if not any((opens, due, milestones, exams)):
            continue
        start = anchor + timedelta(weeks=week-1)
        dates = start.strftime('%b %-d') + '–' + (start+timedelta(days=6)).strftime('%b %-d')
        rows.append([str(week), dates, ', '.join(opens) or '—', ', '.join(due) or '—', ', '.join(milestones) or '—', ', '.join(exams) or '—'])
    header = ['Week', 'Calendar band', 'Assignment opens', 'Assignment due', 'Project deliverable', 'Exam']
    table = '\n'.join('| ' + ' | '.join(row) + ' |' for row in [header, ['---']*len(header), *rows])
    final = next(m for m in project['milestones'] if m['id'] == 'final_report')
    text = '\n\n'.join([
        '# Provisionally frozen assessment timeline',
        'Generated by `python3 scripts/schedule_report.py` from accepted decisions. This renderer only produces the schedule; see the separate Phase 6 audits for validation and limitations.',
        '**Freeze:** ' + schedule['freeze']['scope'] + ' **Reopen:** ' + schedule['freeze']['reopen_trigger'],
        'Calendar bands start October 5, 2026 and continue into January 2027. Exact release/deadline days, exams and makeup sessions are not booked. Calendar weeks must be mapped to the unchanged logical lecture sequence.',
        table,
        '**Assignment constraint:** preserve at least 21 days after prerequisite-ready release. Early Week 7 A1 must be reconciled with the actual Week 4 teaching/makeup dates; do not silently shorten its window. One-week overlaps remain allowed.',
        '**Presentations:** Week 14, online, TA-led and recorded; TA and groups grade. Retain three two-hour slots, up to eight teams each, and own-slot attendance. TA availability, slot allocation, rubric and TA/peer weights remain open.',
        '**Final report:** Week ' + str(final['target_week']) + '; ' + final['deadline_rule'] + '. Confirm compatibility with the official grade deadline.',
        '**Teaching capacity:** 26 lectures retained, with one makeup each in October, November and December. December 31 is assumed unavailable for planning; no official holiday claim is made.',
        '**Regular-semester template:** MT3 early Week 14; presentations late Week 14 or early Week 15, when the instructor is available throughout.',
        'See [reset handoff](../analysis/phase6_handoff.md) for the post-Phase-7 calendar follow-up and Phase 6 status.'
    ]) + '\n'
    return text


def main():
    (ROOT / 'output/assessment_timeline.md').write_text(build())
    print('Rendered accepted schedule snapshot only; no audit or syllabus generation performed.')


if __name__ == '__main__':
    main()
